import os
import sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, SCRIPT_DIR)
from lib import generate_topic

OUT_PATH = os.path.join(SCRIPT_DIR, "..", "data", "meetings-collaboration.json")

# Phrase content below is copied by hand (and lightly cleaned up: casual
# contractions like "gonna" normalized, internal jargon like Jira-specific
# wording trimmed, unclear/overly-narrow one-off lines dropped) from the
# "Meetings & Collaboration" topic (tier "core" / nav tab "Situations"),
# sections A1-A10. A1, A2, A3, A5/A6, and A8 are each split into 2 finer
# sub-groups since they bundle distinct communicative functions (e.g. formal
# opening vs. small talk warm-up; clarifying understanding vs. probing scope;
# proposing ideas vs. probing risk; boundary-setting vs. buying time;
# closing vs. steering a drifting discussion back on track), mirroring how
# generate_core_patterns.py split its H14 into finer sub-groups.
TIER_ID = "core"
TIER_NAME = "Situations"

groups_def = [
    ("Opening & framing the meeting",
     "You've just joined a meeting and need to open it by giving people context before diving into content.",
     "used to open a meeting by giving context or background before the main content",
     [
        ("Before we dive in, let me briefly set the context, so we're all on the same page.",
         "Before we dive in, let me briefly set the context, so we're all on the same page about the vendor delay."),
        ("Before we dive in, let me briefly outline the background, so we're all on the same page.",
         "Before we dive in, let me briefly outline the background, so we're all on the same page on why churn spiked last month."),
        ("Over the past few weeks, we've noticed..., and today's goal is to discuss...",
         "Over the past few weeks, we've noticed a drop in checkout conversion, and today's goal is to discuss what's driving it."),
        ("In our previous meeting, we noticed..., and today's goal is to discuss...",
         "In our previous meeting, we noticed the API latency spike, and today's goal is to discuss the fix timeline."),
        ("I'll start with a quick overview of the background, then we'll go through the key points on the agenda and open it up for discussion.",
         "I'll start with a quick overview of the background, then we'll go through the key points on the agenda and open it up for discussion — should take about 30 minutes."),
        ("Since [name]'s off today, I'll be leading this call.",
         "Since Mark's off today, I'll be leading this call, so let's get started."),
        ("Let's get started.",
         "Let's get started — we have five items on the agenda."),
        ("Let's take a quick look at the agenda.",
         "Let's take a quick look at the agenda before we jump into the roadmap discussion."),
        ("The goal of this meeting is...",
         "The goal of this meeting is to align on the Q3 pricing changes."),
        ("Alright team, let's wait a few more minutes for the rest of the team to join the call.",
         "Alright team, let's wait a few more minutes for the rest of the team to join the call before we start."),
        ("Shall we start?",
         "Shall we start, or is anyone still waiting on a dial-in?"),
        ("Shall we get started?",
         "Shall we get started, or do you want to grab a coffee first?"),
        ("Shall we give it a minute in case anyone else joins?",
         "Shall we give it a minute in case anyone else joins from the design team?"),
     ]),
    ("Small talk & warm-up",
     "You're waiting for the meeting to formally start and want to open with some light, friendly small talk.",
     "used for light social small talk before a meeting officially starts",
     [
        ("Welcome back! How was your holiday?",
         "Welcome back! How was your holiday? I heard you went to Da Nang."),
        ("You look refreshed.",
         "You look refreshed — the time off clearly did you good."),
        ("Great to hear.",
         "Great to hear — glad the trip went well."),
        ("That's amazing.",
         "That's amazing, I've always wanted to visit Sapa."),
     ]),
    ("Clarifying & confirming understanding",
     "You want to make sure you've correctly understood what a colleague just explained.",
     "used to check or confirm that you've correctly understood what was just said",
     [
        ("As I understand it, ...",
         "As I understand it, the client wants the invoice logic changed before the next release."),
        ("From my understanding, ...",
         "From my understanding, the migration is scheduled for next Friday, not this one."),
        ("Maybe I'm missing something, but why do we...?",
         "Maybe I'm missing something, but why do we need sign-off from both legal and finance for this?"),
        ("Let me confirm I understood it correctly.",
         "Let me confirm I understood it correctly: we're pausing the campaign, not cancelling it."),
        ("Just to confirm, we all agree on this approach, right?",
         "Just to confirm, we all agree on this approach, right — phased rollout starting with the EU region?"),
        ("Just to align, are we saying that...?",
         "Just to align, are we saying that tickets should be triaged before they're assigned, not after?"),
        ("Correct me if I'm wrong, but...",
         "Correct me if I'm wrong, but I thought QA already signed off on this build."),
        ("Does that match your expectation?",
         "We're targeting a 20% reduction in load time — does that match your expectation?"),
        ("Does this make sense to you?",
         "That's the proposed data flow — does this make sense to you?"),
        ("Does that make sense so far?",
         "We've covered the pricing tiers and the rollout plan — does that make sense so far?"),
        ("Earlier, you mentioned that XXX, but it seems a bit different here.",
         "Earlier, you mentioned that the API would return null on error, but it seems a bit different here — it's returning an empty array."),
        ("That sounds slightly different from what we discussed earlier.",
         "That sounds slightly different from what we discussed earlier — I thought we'd agreed on a two-week buffer."),
        ("Did I get that right?",
         "So the refund only applies to annual plans — did I get that right?"),
        ("Am I correct?",
         "You're saying the outage only affected EU customers — am I correct?"),
        ("Sorry, could you please go over the last point again?",
         "Sorry, could you please go over the last point again? I lost you around the pricing tiers."),
        ("Could you quickly recap that for us?",
         "Could you quickly recap that for us — some folks joined late."),
        ("I'm not quite sure I understand it completely — could you help explain it in more detail, as if for a beginner?",
         "I'm not quite sure I understand the approval workflow completely — could you help explain it in more detail, as if for a beginner?"),
        ("Can you go back to the previous slide for a moment? I have a quick question there.",
         "Can you go back to the previous slide for a moment? I have a quick question about the churn numbers."),
     ]),
    ("Probing scope, outcomes & follow-up",
     "You're reviewing a new requirement and want to understand its intended scope and outcome before committing.",
     "used to probe the scope, outcome, or current relevance of a requirement or task",
     [
        ("What's the expected outcome here?",
         "Before we scope this, what's the expected outcome here — fewer support tickets, or faster resolution time?"),
        ("How would this behave in X situation?",
         "How would this behave if a user submits the form twice in a row?"),
        ("On which scenarios?",
         "You said it only applies sometimes — on which scenarios exactly?"),
        ("Let's say...",
         "Let's say the payment fails halfway through — what happens to the order status?"),
        ("What if we...?",
         "What if we cached the results instead of hitting the API every time?"),
        ("Are these now the new top priority?",
         "With the client escalation, are these three tickets now the new top priority?"),
        ("Is this still relevant?",
         "This ticket is from last quarter's roadmap — is this still relevant?"),
        ("What's changed since last time?",
         "What's changed since last time we discussed the onboarding flow?"),
     ]),
    ("Proposing & explaining ideas",
     "You want to propose a possible solution to the group without sounding overly definite.",
     "used to propose a possible solution or approach without sounding overly definite",
     [
        ("One possible option could be to...",
         "One possible option could be to cache the results for five minutes to reduce load."),
        ("One way to handle this would be...",
         "One way to handle this would be to split the release into two smaller batches."),
        ("It might make more sense to...",
         "It might make more sense to fix the root cause first, before patching the symptom."),
        ("We might want to consider...",
         "We might want to consider a soft launch to a small user segment first."),
        ("Here's how",
         "Here's how — we run the migration overnight when traffic is lowest."),
        ("Here's why",
         "Here's why — the current schema can't support multi-currency pricing."),
        ("Here's the thing",
         "Here's the thing — the vendor's SLA doesn't actually cover weekend outages."),
        ("Here's what I think — here's what to do.",
         "Here's what I think — here's what to do: freeze new tickets until the backlog is under twenty."),
        ("That's the overall flow — dive into this, the steps would be: ...",
         "That's the overall flow — dive into this, the steps would be: validate input, call the pricing service, then confirm the order."),
        ("So our approach has always been: build what we're asked to build.",
         "So our approach has always been: build what we're asked to build, and if they ask for more later, we'll build more then."),
     ]),
    ("Probing problem & risk before deciding",
     "Before agreeing to a new requirement, you want the team to first pin down the underlying problem and its risks.",
     "used to push the group to define the underlying problem and risks before committing to a solution",
     [
        ("What problem are we trying to solve for the user with this requirement?",
         "Before we build this, what problem are we trying to solve for the user with this requirement?"),
        ("What specific outcomes are we expecting from this feature?",
         "What specific outcomes are we expecting from this feature — higher retention, or fewer support calls?"),
        ("The risk I see here is...",
         "The risk I see here is that we're optimizing for one customer segment at the expense of everyone else."),
        ("What are the potential downsides or unintended consequences if we implement this?",
         "What are the potential downsides or unintended consequences if we implement this without a rollback plan?"),
     ]),
    ("Polite disagreement & pushback",
     "You disagree with a colleague's suggestion but want to push back without creating tension.",
     "used to push back on a colleague's suggestion without creating tension",
     [
        ("I see your point, but I'm a bit concerned about XXX.",
         "I see your point, but I'm a bit concerned about the timeline — two weeks feels tight for a full migration."),
        ("I see where you're coming from, but I think the real issue is...",
         "I see where you're coming from, but I think the real issue is our onboarding flow, not the pricing."),
        ("That's a fair point, though I have some concerns.",
         "That's a fair point, though I have some concerns about how this scales past 10,000 users."),
        ("I'm not convinced that's the best approach.",
         "I'm not convinced that's the best approach — have we considered a phased rollout instead?"),
        ("I'd challenge that assumption.",
         "I'd challenge that assumption — are we sure demand is actually flat, or just under-measured?"),
        ("I'm not sure I agree.",
         "I'm not sure I agree — the last two surveys said otherwise."),
        ("I see it slightly differently.",
         "I see it slightly differently — I'd prioritize stability over new features this sprint."),
        ("That might be true, but...",
         "That might be true, but it still doesn't explain the drop in retention."),
        ("I think we might be missing something.",
         "I think we might be missing something — the numbers don't add up to last quarter's report."),
        ("Let's pressure-test that idea.",
         "Let's pressure-test that idea before we commit engineering time to it."),
        ("I understand the logic, though I have some concerns.",
         "I understand the logic, though I have some concerns about the compliance implications."),
        ("Can we explore an alternative?",
         "Can we explore an alternative that doesn't require a full database migration?"),
        ("With all due respect, I think we're looking at the wrong problem.",
         "With all due respect, I think we're looking at the wrong problem — this is a messaging issue, not a pricing one."),
        ("I hear what you're saying, and I'd agree if the numbers backed it up.",
         "I hear what you're saying, and I'd agree if the numbers backed it up, but churn actually went down last month."),
        ("That works technically, but it creates this user impact.",
         "That works technically, but it creates this user impact — customers would lose their saved carts."),
        ("I'm not saying you're wrong. I'm saying there's more to it.",
         "I'm not saying you're wrong. I'm saying there's more to it than just the server load."),
        ("There's another blind spot there.",
         "There's another blind spot there — we haven't tested this on the free tier accounts."),
     ]),
    ("Boundaries & pushback under pressure",
     "A manager keeps adding more work to your plate, and you need to set a boundary without being confrontational.",
     "used to set a boundary or push back when asked to take on more work than is reasonable",
     [
        ("I'm pretty tied up with project tasks and can't take on any more work right now.",
         "I'm pretty tied up with project tasks this sprint and can't take on any more work right now."),
        ("Taking on these items would put our current commitments at risk.",
         "Taking on these three extra tickets would put our current sprint commitments at risk."),
        ("We'd need to deprioritize existing work before we could pick these up.",
         "We'd need to deprioritize the reporting dashboard before we could pick these up."),
        ("Fully committed.",
         "The whole team is fully committed through the end of this sprint."),
        ("Fully allocated.",
         "Engineering is fully allocated to the migration until Friday."),
        ("If it's a massive piece of work, I think the idea is not to do it.",
         "If it's a massive piece of work like a full redesign, I think the idea is not to do it this sprint."),
        ("I do apologise for the stress this causes.",
         "I do apologise for the stress this causes — we're doing our best to unblock you quickly."),
        ("Out of scope for now — we're de-prioritising that until somebody asks for it.",
         "Out of scope for now — we're de-prioritising the dark mode request until somebody asks for it."),
        ("If it's 10 minutes of work, yes. If it's half a day of work, then no.",
         "If it's 10 minutes of work, yes, I can squeeze it in. If it's half a day of work, then no, not this week."),
        ("Look, I'm not allowed to decide on requirements — that's the PO's scope. I'll take your question, pass it to her, and update you once I have an answer.",
         "Look, I'm not allowed to decide on requirements — that's the PO's scope. I'll take your question, pass it to her, and update you once I have an answer, no shortcuts."),
        ("I wish I could — but I'm not the owner. If I decide and it flips later, we're both in trouble.",
         "I wish I could sign off on this — but I'm not the owner. If I decide and it flips later, we're both in trouble."),
        ("That's not on the table.",
         "A full refund isn't on the table, but we can offer a credit."),
        ("That's not how I operate.",
         "I don't cut corners under pressure — that's not how I operate."),
        ("There is no try — take it and commit, or don't take it at all.",
         "There is no try on this ticket — take it and commit, or don't take it at all."),
     ]),
    ("Buying time",
     "You've just been asked a question you're not ready to answer and need a moment before responding.",
     "used to stall briefly or postpone an answer when you're not ready to respond",
     [
        ("I'm not 100% sure on that — let me run it by engineering real quick. I'll have an answer by tomorrow.",
         "I'm not 100% sure on that — let me run it by engineering real quick. I'll have an answer by tomorrow morning."),
        ("Honestly? I need to double-check with the team. Can we hold this till morning?",
         "Honestly? I need to double-check with the team on the rollback plan. Can we hold this till morning?"),
        ("I'm noting it down — give me a minute. I might not get it in the first call.",
         "I'm noting it down — give me a minute, I might not catch it all in the first call."),
        ("Give me a second.",
         "Give me a second — let me pull up the actual numbers."),
        ("Let me think about that for a second.",
         "Let me think about that for a second before I commit to a date."),
        ("My initial thought is...",
         "My initial thought is we should wait for the QA results before deciding."),
        ("That's a good question, let me take this offline and get back to you after this session.",
         "That's a good question about data retention, let me take this offline and get back to you after this session."),
        ("That's a good question, let me double-check and get back to you after this session.",
         "That's a good question about the refund policy, let me double-check and get back to you after this session."),
        ("I don't want to give an inaccurate answer. Let me validate this today and confirm by end of day.",
         "I don't want to give an inaccurate answer on the pricing change. Let me validate this today and confirm by end of day."),
        ("I need more time to think and will let you know later.",
         "I need more time to think about the trade-offs here and will let you know later today."),
        ("Two minutes — I'll ping the PO now.",
         "Two minutes — I'll ping the PO now to confirm the requirement."),
        ("Bear with me a minute.",
         "Bear with me a minute, I'm pulling up the dashboard."),
        ("Oops, bear with me.",
         "Oops, bear with me — wrong tab, one second."),
        ("I'm not ignoring you, I'm just thinking.",
         "I'm not ignoring you, I'm just thinking through the edge cases before I answer."),
     ]),
    ("Status updates & blockers",
     "You need to give the team a quick update on where a task stands and flag anything blocking it.",
     "used to give a status update or flag something blocking progress",
     [
        ("This is blocked by...",
         "This is blocked by the vendor's API — we're waiting on their fix."),
        ("I'll flag this as a risk.",
         "I'll flag this as a risk in the sprint review — the timeline is tight."),
        ("I'll flag it — the PO will see it and we can sort it later.",
         "I'll flag it in the backlog — the PO will see it and we can sort it later."),
        ("We're on track for...",
         "We're on track for the Friday release, assuming QA passes today."),
        ("I'm currently lining things up for...",
         "I'm currently lining things up for next sprint's payment work."),
        ("Will this be wrapped up before you're unavailable again on Wednesday?",
         "Will the migration script be wrapped up before you're unavailable again on Wednesday?"),
        ("Could you prioritize the rule-related tickets?",
         "Could you prioritize the rule-related tickets before the compliance review?"),
        ("There's nothing new on this, apart from other tickets.",
         "There's nothing new on this feature, apart from the two dependent tickets."),
        ("I don't expect many major changes, apart from what we already discussed.",
         "I don't expect many major changes to the API, apart from what we already discussed."),
        ("This one needs a bit more investigation.",
         "This one needs a bit more investigation before I can give an ETA."),
        ("I need a concrete answer, not a general direction.",
         "I need a concrete answer on the launch date, not a general direction."),
        ("Who owns this?",
         "The ticket has been sitting untouched for a week — who owns this?"),
        ("Someone needs to own this.",
         "Someone needs to own this before it slips through the cracks again."),
     ]),
    ("Closing & next steps",
     "You're wrapping up the meeting and want to confirm there's nothing left before closing.",
     "used to wrap up a meeting and confirm there's nothing left before closing",
     [
        ("Before I conclude, does anyone have any questions or concerns?",
         "Before I conclude, does anyone have any questions or concerns about the rollout plan?"),
        ("Any final thoughts?",
         "Any final thoughts before we close out the sprint review?"),
        ("If there are no further comments, I'll wrap this up and move forward with the next steps.",
         "If there are no further comments, I'll wrap this up and move forward with the next steps on hiring."),
        ("Are we good to proceed with this?",
         "Are we good to proceed with this rollout plan?"),
        ("Are we happy to move status to 'Ready to Code'?",
         "The requirements look clear now — are we happy to move status to 'Ready to Code'?"),
        ("Nothing else from my side.",
         "Nothing else from my side — the design is finalized."),
        ("That's all from me.",
         "That's all from me, over to the QA team for their update."),
        ("I'm done on my part. Over to you.",
         "I'm done on my part, the backend is ready. Over to you for the frontend integration."),
        ("I'll take that as no.",
         "No one's objected in the last minute — I'll take that as no."),
        ("So we're agreed. Let's not revisit this.",
         "So we're agreed on the March launch date. Let's not revisit this."),
        ("That's settled. Next item.",
         "That's settled — vendor B it is. Next item."),
        ("I'll circle back once it's confirmed.",
         "I'll circle back once the budget is confirmed by finance."),
        ("Let me know how you want to proceed with this.",
         "Let me know how you want to proceed with this — I can start either way."),
        ("Appreciate your input on this.",
         "Appreciate your input on this, it really helped clarify the scope."),
        ("Cool. Let's wrap this up then. Thanks for your time.",
         "Cool. Let's wrap this up then. Thanks for your time, everyone."),
        ("Anything else? Or are we good to wrap?",
         "Anything else? Or are we good to wrap and send out the notes?"),
        ("Let's table that and come back to it at the end.",
         "Let's table that pricing debate and come back to it at the end."),
        ("Let's park that for now.",
         "Let's park that for now and revisit once we have the Q3 numbers."),
        ("What does success look like at the end of this?",
         "Before we wrap, what does success look like at the end of this project?"),
        ("I want that in the minutes.",
         "We agreed to a two-week buffer — I want that in the minutes."),
     ]),
    ("Staying focused / steering back",
     "The discussion has drifted off-topic and you want to bring the group back to the main agenda.",
     "used to bring a drifting discussion back to the main agenda item",
     [
        ("Let's stay focused.",
         "Let's stay focused — we can discuss the rebrand separately."),
        ("Let's stick to the agenda.",
         "Let's stick to the agenda, we only have ten minutes left."),
        ("One thing at a time.",
         "One thing at a time — let's finish the pricing discussion first."),
     ]),
    ("Tech glitches on call",
     "Your connection is glitching during a call and you need to let the others know.",
     "used to flag a technical glitch or connection issue during a call",
     [
        ("A bit of lag — froze for a moment, let me refresh and brb.",
         "A bit of lag — froze for a moment during the demo, let me refresh and brb."),
        ("My mic's having an issue.",
         "My mic's having an issue, can everyone still hear me okay?"),
        ("Let's switch to chat, or I'll email you the rest?",
         "Let's switch to chat, or I'll email you the rest of the notes?"),
        ("You still with me?",
         "You still with me? I think we lost you for a second."),
        ("You still there?",
         "You still there? Your video just froze."),
        ("...you just dropped — can you hear me?",
         "You just dropped — can you hear me now?"),
        ("Hang on — can you say that again? Not sure I caught it.",
         "Hang on — can you say that again? Not sure I caught the number."),
        ("Hey, we lost connection — want to pick up where we left off?",
         "Hey, we lost connection for a bit there — want to pick up where we left off?"),
     ]),
    ("Personal check-in & texting",
     "A colleague has gone quiet on chat and you want to gently check if they're still there.",
     "used to gently check in on a colleague who's gone quiet in chat or on a call",
     [
        ("I see you're typing.",
         "I see you're typing — take your time, no rush."),
        ("Looks like you're typing.",
         "Looks like you're typing a long reply, I'll wait."),
        ("Hey are you still there? Or did I lose you?",
         "Hey are you still there? Or did I lose you when the wifi dropped?"),
        ("Everything okay on your end?",
         "You've been quiet for a bit — everything okay on your end?"),
        ("Take your time. I'll wait. No rush.",
         "Take your time drafting the reply. I'll wait. No rush."),
        ("No worries — I'll let you go. Just text me when you're free.",
         "No worries — I'll let you go. Just text me when you're free to finish this."),
        ("When works for you next?",
         "No worries if now's bad — when works for you next?"),
        ("Let me switch devices.",
         "Let me switch devices, my laptop's about to die."),
     ]),
]

if __name__ == "__main__":
    generate_topic(
        out_path=OUT_PATH,
        exam_id="meetings-collaboration",
        title="Chunk Atlas — Situations: Meetings & Collaboration",
        tier_id=TIER_ID,
        tier_name=TIER_NAME,
        groups_def=groups_def,
    )
