import os
import sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, SCRIPT_DIR)
from lib import generate_topic

OUT_PATH = os.path.join(SCRIPT_DIR, "..", "data", "persuasion-debate.json")

# Phrase content below is copied by hand from the "Persuasion & High-Stakes
# Debate" topic (tier "core" / nav tab "Situations"), sections C1-C6 and
# N1-N10. C7 is skipped: it's meta-advice about internalizing a confident
# mindset (explicitly labeled "to internalize, not to recite" in the
# source), not a set of quizzable chunks, mirroring how
# generate_core_patterns.py skipped its H15. C1-C5 (character-styled
# assertive/persuasive lines) are kept as distinct functional registers
# and relabeled with plain English function names instead of the TV-persona
# names used as internal headers in the source. C6 bundles several distinct
# workplace-persuasion functions (framing trade-offs, negotiating scope,
# confirming decisions) and is split into 3 finer sub-groups, mirroring how
# generate_core_patterns.py split its H14.
TIER_ID = "core"
TIER_NAME = "Situations"

groups_def = [
    ("Assertive positioning & control",
     "You need to project total confidence and control in a high-stakes negotiation, without appearing arrogant.",
     "used to project confidence and control in a high-stakes negotiation",
     [
        ("When you're the best in the room, you don't need to prove it.",
         "When you're the best in the room, you don't need to prove it — let the proposal speak for itself."),
        ("I don't take cases I can't win. This is one I can win.",
         "I don't take deals I can't win. This one, with the right terms, is one we can win."),
        ("My track record speaks for itself.",
         "My track record speaks for itself — three successful launches in two years."),
        ("Here's what's going to happen.",
         "Here's what's going to happen: we present the revised terms Monday, and we hold firm on the deadline."),
        ("I don't care what the other side wants. What do we need?",
         "I don't care what the other side wants to open with. What do we need to walk away with?"),
        ("The moment you blink, you've lost.",
         "The moment you blink on the price in that room, you've lost — hold the line."),
        ("Confidence isn't arrogance. It's preparation.",
         "Confidence isn't arrogance. It's preparation — I've read every page of that contract twice."),
        ("You're not here to be liked. You're here to be effective.",
         "You're not here to be liked in this negotiation. You're here to be effective."),
        ("Stop thinking about what could go wrong. Think about what needs to go right.",
         "Stop thinking about what could go wrong with the pitch. Think about what needs to go right."),
        ("If you walk in that room looking nervous, you've already lost.",
         "If you walk into that boardroom looking nervous, you've already lost half the argument."),
     ]),
    ("Persuading through logic & analysis",
     "You want to win an argument by walking someone through the data and reasoning, step by step.",
     "used to persuade someone by walking them through data and reasoning, step by step",
     [
        ("Let me walk you through the numbers on this.",
         "Let me walk you through the numbers on this before you decide — churn actually dropped after the price increase."),
        ("If you look at it from a different angle, here's what you see.",
         "If you look at it from a different angle, here's what you see: the delay actually saved us from a bigger recall."),
        ("Technically speaking, you're right — but practically, it doesn't hold.",
         "Technically speaking, you're right that it's cheaper — but practically, it doesn't hold once you factor in support costs."),
        ("With all due respect, I think we're looking at the wrong problem.",
         "With all due respect, I think we're looking at the wrong problem — this is a retention issue, not an acquisition one."),
        ("That argument works in theory, but not in practice.",
         "That argument works in theory, but not in practice — we tried a flat rate and it confused customers."),
        ("That's a fair point — but consider this.",
         "That's a fair point about cost — but consider this: switching vendors now would delay the launch by two months."),
        ("Before we go any further, I need to flag something important.",
         "Before we go any further, I need to flag something important about the contract's termination clause."),
        ("Have you considered what happens if we're wrong about that?",
         "Have you considered what happens if we're wrong about the demand forecast?"),
        ("What if we approach this from a completely different direction?",
         "What if we approach this from a completely different direction — license the technology instead of building it?"),
        ("I've thought about this carefully and I stand by it.",
         "I've thought about this carefully and I stand by it: we should walk away if they won't move on price."),
        ("I'm not asking you to trust me. I'm asking you to trust the analysis.",
         "I'm not asking you to trust me. I'm asking you to trust the analysis — the model has been right three quarters running."),
     ]),
    ("Reading the room & tactful handling",
     "You need to handle a sensitive situation with tact, reading between the lines without escalating it.",
     "used to handle a sensitive situation with tact, without escalating it",
     [
        ("You might want to rethink that before it becomes a problem.",
         "You might want to rethink cc'ing legal on that email before it becomes a problem."),
        ("Something is off about this. I don't know what yet, but I'll find out.",
         "Something is off about this vendor's numbers. I don't know what yet, but I'll find out before we sign."),
        ("Let's handle this quietly before it becomes loud.",
         "Let's handle this client complaint quietly before it becomes loud on social media."),
        ("That's not going to happen, but here's what I can do instead.",
         "A full refund isn't going to happen, but here's what I can do instead — a service credit and an apology call."),
        ("I appreciate you asking. The answer is still no.",
         "I appreciate you asking again about the exception. The answer is still no."),
        ("I'm going to stop you right there.",
         "I'm going to stop you right there before this turns into a blame conversation."),
        ("I'll look into it. That's the best I can offer you right now.",
         "I'll look into the billing discrepancy. That's the best I can offer you right now."),
        ("I've already handled it. You're welcome.",
         "I've already handled the escalation with the client. You're welcome."),
        ("Let me manage that relationship for you. You focus on the deal.",
         "Let me manage the vendor relationship for you. You focus on closing the deal."),
        ("The optics on this matter more than you think.",
         "The optics on laying off the team right after the bonus announcement matter more than you think."),
     ]),
    ("Setting boundaries & requiring respect",
     "You're negotiating terms and need to draw a firm, non-negotiable line without sounding hostile.",
     "used to draw a firm, non-negotiable boundary in a negotiation without sounding hostile",
     [
        ("If we're doing this, we're doing it correctly. No shortcuts.",
         "If we're doing this integration, we're doing it correctly. No shortcuts on the security review."),
        ("I need people on my team who want to be excellent, not just adequate.",
         "I need people on my team who want to be excellent, not just adequate, on this launch."),
        ("I want what I was promised. Nothing more, nothing less.",
         "I want what I was promised in the offer letter. Nothing more, nothing less."),
        ("These are my terms. They are not flexible.",
         "These are my terms for the renewal. They are not flexible on the annual price floor."),
        ("Let's be clear about what each of us is bringing to this arrangement.",
         "Let's be clear about what each of us is bringing to this partnership before we sign anything."),
        ("I will not agree to something I haven't fully reviewed.",
         "I will not agree to the new SLA terms — I haven't fully reviewed the penalty clauses yet."),
        ("Don't ask me to cut corners on something this important.",
         "Don't ask me to cut corners on the security audit — it's too important to rush."),
     ]),
    ("Decisive leadership & vision",
     "As a leader, you need to make a hard call and rally the team behind it with conviction.",
     "used by a leader to make a hard call and rally the team behind it with conviction",
     [
        ("I've made the call. Now we execute.",
         "I've made the call to delay the launch by two weeks. Now we execute."),
        ("Don't bring me problems without solutions.",
         "Don't bring me problems without solutions — come with at least one option."),
        ("This firm does not react. This firm leads.",
         "This company does not react to every competitor move. This company leads."),
        ("We are not playing catch-up. We are setting the pace.",
         "We are not playing catch-up on AI features. We are setting the pace."),
        ("Short-term loss, long-term position. That's the trade-off I'm willing to make.",
         "Short-term loss, long-term position — cutting this quarter's margin to win the enterprise segment is the trade-off I'm willing to make."),
        ("Every decision we make has to serve the bigger picture.",
         "Every decision we make this quarter has to serve the bigger picture: becoming the category leader."),
        ("Don't win the battle and lose the war.",
         "Don't win the pricing argument and lose the war — the client's still walking away unhappy."),
        ("Think two moves ahead. Always.",
         "Think two moves ahead, always — what does the competitor do if we cut prices tomorrow?"),
     ]),
    ("Framing business context & trade-offs",
     "You're presenting a business decision and need to frame the trade-offs clearly for a mixed technical and business audience.",
     "used to frame a decision's business trade-offs clearly for a mixed technical/business audience",
     [
        ("The objective of today's discussion is...",
         "The objective of today's discussion is to decide between the two vendor proposals."),
        ("Let me set the baseline so we're aligned.",
         "Let me set the baseline so we're aligned: current churn is 4.5%, and our target is under 3%."),
        ("From a business perspective, this impacts...",
         "From a business perspective, this delay impacts our ability to close the enterprise deal this quarter."),
        ("The trade-off here is between speed and accuracy.",
         "The trade-off here is between speed and accuracy — the faster model gets it right 90% of the time."),
        ("I understand the technical constraint. From a business standpoint, the risk is...",
         "I understand the technical constraint on real-time sync. From a business standpoint, the risk is losing customers who expect instant updates."),
        ("That works technically, but it creates this user impact.",
         "That works technically, but it creates this user impact — customers would need to re-enter their payment details."),
        ("On the surface it looks small, but it impacts logic, testing, and timelines.",
         "On the surface this field change looks small, but it impacts logic, testing, and timelines across three teams."),
     ]),
    ("Clarifying scope & negotiating constraints",
     "You're negotiating the scope of a request and need to understand what's actually fixed versus flexible.",
     "used to negotiate scope and clarify what constraints are actually fixed versus flexible",
     [
        ("Can we explore an alternative that still meets compliance?",
         "Can we explore an alternative that still meets compliance, but doesn't require a full data migration?"),
        ("Help me understand the limitation — what's negotiable?",
         "Help me understand the budget limitation — what's negotiable, the timeline or the scope?"),
        ("That's a valid idea, but it's outside the current scope.",
         "That's a valid idea, but it's outside the current scope of this release."),
        ("If we add this, we'll need to adjust timeline or resources.",
         "If we add multi-currency support, we'll need to adjust the timeline or bring in another engineer."),
        ("Understood. Let's clarify whether it's a hard constraint or a design choice.",
         "Understood. Let's clarify whether the two-step approval is a hard compliance constraint or just a design choice."),
        ("I agree simplicity is important. The challenge is that the 'simple way' doesn't cover these risks. What I'm proposing is the simplest option that still meets compliance.",
         "I agree simplicity is important. The challenge is that the 'simple way' doesn't cover data residency risks. What I'm proposing is the simplest option that still meets compliance."),
     ]),
    ("Confirming decisions & next steps",
     "You've walked the group through the analysis and want to lock in a decision and clear owners before ending the discussion.",
     "used to lock in a decision and assign clear owners before ending a business discussion",
     [
        ("What we know so far is...",
         "What we know so far is that mobile users convert at half the rate of desktop users."),
        ("I'll separate facts from assumptions here.",
         "I'll separate facts from assumptions here: we know churn rose, we're assuming it's the price change."),
        ("Let's prioritize based on business value.",
         "Let's prioritize based on business value — the reporting feature affects the most revenue."),
        ("What problem are we trying to solve first?",
         "Before we scope the roadmap, what problem are we trying to solve first — retention or acquisition?"),
        ("To summarize, we've agreed on...",
         "To summarize, we've agreed on the phased rollout starting with the EU region."),
        ("Next steps are clear: X owns A, Y owns B.",
         "Next steps are clear: Sarah owns the vendor contract, and I own the internal rollout plan."),
        ("If there's no objection, we'll proceed with this.",
         "If there's no objection, we'll proceed with this pricing structure starting next month."),
        ("Yes, based on current data and constraints, this is the most balanced option. That said, I'm open to adjusting if new information comes in.",
         "Yes, based on current data and constraints, vendor B is the most balanced option. That said, I'm open to adjusting if new information comes in."),
        ("I don't want to give an inaccurate answer. Let me validate this today and confirm by end of day.",
         "I don't want to give an inaccurate answer on the renewal terms. Let me validate this today and confirm by end of day."),
     ]),
    ("Reframing the issue",
     "The group is debating the wrong question, and you want to redirect everyone to the question that actually matters.",
     "used to redirect a debate toward the question that actually matters",
     [
        ("I think the real question here isn't X, it's Y.",
         "I think the real question here isn't whether we can afford this, it's whether we can afford not to."),
        ("Let's zoom out for a second — what are we actually trying to solve for?",
         "Let's zoom out for a second — what are we actually trying to solve for, revenue or market share?"),
        ("Rather than asking 'should we do this,' I think the more useful question is 'what would need to be true for this to work.'",
         "Rather than asking 'should we enter this market,' I think the more useful question is 'what would need to be true for this to work.'"),
        ("Can we separate the decision from the person who proposed it?",
         "Can we separate the decision from the person who proposed it? I want to evaluate the plan on its own merits."),
        ("I'd like to reframe this: it's not a cost question, it's a risk-allocation question.",
         "I'd like to reframe this: it's not a cost question, it's a risk-allocation question between us and the vendor."),
        ("So far we've been treating this as a binary choice — but there might be a third option we haven't named yet.",
         "So far we've been treating build-versus-buy as a binary choice — but there might be a partnership option we haven't named yet."),
        ("Let's put the timeline aside for a moment and talk about what 'done' actually looks like.",
         "Let's put the timeline aside for a moment and talk about what 'done' actually looks like for this migration."),
        ("Before we debate the solution, can we agree on what problem we're solving?",
         "Before we debate which vendor to pick, can we agree on what problem we're actually solving?"),
     ]),
    ("Challenging assumptions",
     "You suspect the group's plan rests on an assumption nobody has actually verified, and you want to test it before moving forward.",
     "used to test an unverified assumption underlying a plan before the group commits to it",
     [
        ("What has to be true for this plan to succeed?",
         "What has to be true for this expansion plan to succeed — that demand holds, or that our costs stay flat?"),
        ("I want to pressure-test an assumption we've all been making — that demand will stay flat.",
         "I want to pressure-test an assumption we've all been making — that our biggest customer will renew regardless of price."),
        ("Where does that number actually come from?",
         "Where does that 30% growth number actually come from — last year's data, or this year's pipeline?"),
        ("Help me understand the logic that gets us from A to B.",
         "Help me understand the logic that gets us from a 10% discount to a 25% increase in sign-ups."),
        ("Is that a fact, or is that something we're assuming because it's always been done that way?",
         "Is that a fact, or is that something we're assuming because it's always been priced that way?"),
        ("What would have to change for that assumption to no longer hold?",
         "What would have to change for the assumption that shipping costs stay flat to no longer hold?"),
        ("I noticed we're treating this as certain — how confident are we, really?",
         "I noticed we're treating the Q4 forecast as certain — how confident are we, really?"),
        ("If we're wrong about that one assumption, does the whole plan fall apart?",
         "If we're wrong about that one assumption on retention, does the whole three-year plan fall apart?"),
        ("Let's stress-test this before we bring it to the board.",
         "Let's stress-test this revenue model before we bring it to the board."),
     ]),
    ("Steelmanning the other side",
     "Before countering an opposing view, you want to first present it in its strongest, fairest form.",
     "used to present an opposing view in its strongest, fairest form before countering it",
     [
        ("Let me make sure I'm representing your position fairly: you're saying that...",
         "Let me make sure I'm representing your position fairly: you're saying that the risk outweighs the potential upside."),
        ("If I were arguing your side, I'd say...",
         "If I were arguing your side, I'd say the vendor's price is justified by their reliability record."),
        ("Steelmanning your point for a second — the strongest version of that argument is...",
         "Steelmanning your point for a second — the strongest version of that argument is that we'd lose our best engineers to burnout."),
        ("I actually think there's a stronger case for your position than what you've laid out, which is...",
         "I actually think there's a stronger case for your position than what you've laid out, which is that customers may not notice the difference at all."),
        ("Let's look at this from the board's perspective for a moment.",
         "Let's look at this from the board's perspective for a moment — they'll want to know why margins dipped first."),
        ("If I put myself in the customer's shoes, this is what concerns me.",
         "If I put myself in the customer's shoes, this is what concerns me: the price increase with no visible new features."),
        ("What would someone who disagrees with me say right now?",
         "What would someone who disagrees with me say right now about cutting the marketing budget?"),
     ]),
    ("Exposing logic gaps without attacking",
     "You suspect there's a hole in someone's argument and want to surface it without putting them on the defensive.",
     "used to surface a gap in someone's argument without putting them on the defensive",
     [
        ("Walk me through how that would actually play out in practice.",
         "Walk me through how that discount strategy would actually play out in practice with our current margins."),
        ("What happens to this plan if [specific condition] doesn't hold?",
         "What happens to this plan if the vendor's delivery date doesn't hold?"),
        ("I'm not seeing how we get from this data to that conclusion — can you connect the dots for me?",
         "I'm not seeing how we get from a 5% survey response rate to that conclusion — can you connect the dots for me?"),
        ("That's one explanation — what's another one that also fits the data?",
         "That's one explanation for the drop — what's another one that also fits the data?"),
        ("If that's true, how do we explain [contradicting fact]?",
         "If that's true, how do we explain the fact that our top competitor raised prices and grew?"),
        ("I want to make sure this holds up — what's the strongest objection someone could raise to this?",
         "I want to make sure this pricing model holds up — what's the strongest objection someone could raise to it?"),
        ("Where do you see the biggest risk in this argument?",
         "Where do you see the biggest risk in this argument for entering the new market?"),
        ("That logic works at a high level — does it still hold when you apply it to [specific case]?",
         "That logic works at a high level — does it still hold when you apply it to our enterprise customers specifically?"),
     ]),
    ("Persuading with calibrated questions",
     "Instead of arguing your case directly, you want to guide the other person toward the conclusion through questions.",
     "used to guide someone toward a conclusion through open, calibrated questions rather than direct argument",
     [
        ("What would it take for you to feel comfortable moving forward with this?",
         "What would it take for you to feel comfortable moving forward with the new vendor?"),
        ("What's the cost of waiting another quarter to decide?",
         "What's the cost of waiting another quarter to decide on the platform migration?"),
        ("If we did nothing, what's the most likely outcome?",
         "If we did nothing about the churn rate, what's the most likely outcome six months from now?"),
        ("What would need to happen for you to say yes to this?",
         "What would need to happen for you to say yes to the expanded budget?"),
        ("How does this compare to the alternative you're currently leaning towards?",
         "How does this proposal compare to the alternative you're currently leaning towards?"),
        ("What's the one thing that would change your mind here?",
         "What's the one thing that would change your mind about delaying the launch?"),
        ("Six months from now, looking back, what would make you glad we made this call?",
         "Six months from now, looking back, what would make you glad we made this call on pricing?"),
     ]),
    ("Controlling the room",
     "You're facilitating a high-stakes meeting that's drifting, and you need to steer it firmly back toward a decision.",
     "used to firmly steer a drifting high-stakes meeting back toward a decision",
     [
        ("Let's park that thread and come back to it — I don't want to lose the main decision we need today.",
         "Let's park that thread on branding and come back to it — I don't want to lose the main pricing decision we need today."),
        ("Before we go further, can we align on what decision we actually need to leave this room with?",
         "Before we go further, can we align on what decision we actually need to leave this room with today?"),
        ("I want to make sure every voice gets heard on this — what's your take?",
         "I want to make sure every voice gets heard on this — Priya, what's your take?"),
        ("We have three minutes left on this topic — let's make sure we land somewhere concrete.",
         "We have three minutes left on this topic — let's make sure we land somewhere concrete before moving on."),
        ("That's an important point, but a different decision — can we capture it separately and stay focused here?",
         "That's an important point about staffing, but a different decision — can we capture it separately and stay focused here on the budget?"),
        ("Let's not let the exception drive the whole policy.",
         "Let's not let one client's exception drive the whole refund policy."),
        ("I'll take the ownership question offline so we can keep moving.",
         "I'll take the ownership question offline so we can keep moving on the timeline."),
     ]),
    ("Pre-wiring & building coalition",
     "Before a high-stakes meeting, you want to quietly line up support and surface objections in advance.",
     "used to quietly line up support and surface objections before a high-stakes meeting",
     [
        ("Before we bring this to the wider group, I wanted to get your read on it first.",
         "Before we bring this to the wider group, I wanted to get your read on the restructuring plan first."),
        ("I'd like to socialize this idea with a few people before it goes to committee.",
         "I'd like to socialize this pricing idea with a few people before it goes to the pricing committee."),
        ("Is there anything in here that would be a hard no for you? I'd rather know now than in the room.",
         "Is there anything in this proposal that would be a hard no for you? I'd rather know now than in the room."),
        ("Who else needs to be comfortable with this before we present it?",
         "Who else needs to be comfortable with this restructuring before we present it to the board?"),
        ("I want to walk in aligned, not debate this live in front of the board.",
         "I want to walk in aligned on the numbers, not debate this live in front of the board."),
        ("Can I get five minutes with you before Thursday's meeting to preview this?",
         "Can I get five minutes with you before Thursday's meeting to preview the acquisition proposal?"),
     ]),
    ("Handling senior pushback",
     "A senior leader is pushing back hard on your proposal, and you need to respond with confidence, not defensiveness.",
     "used to respond to a senior leader's pushback with confidence, without becoming defensive",
     [
        ("That's a fair challenge — let me walk you through the reasoning, and please push back where it doesn't hold.",
         "That's a fair challenge — let me walk you through the pricing reasoning, and please push back where it doesn't hold."),
        ("I hear the concern. Let me address it directly rather than around it.",
         "I hear the concern about margin. Let me address it directly rather than around it."),
        ("You're right that there's real risk here — here's how we're planning to mitigate it.",
         "You're right that there's real risk in the timeline — here's how we're planning to mitigate it with a phased rollout."),
        ("I don't have a perfect answer, but here's the most defensible one given what we know today.",
         "I don't have a perfect answer on churn, but here's the most defensible one given what we know today."),
        ("If you had to bet, what would make you more confident in this direction?",
         "If you had to bet, what would make you more confident in this direction — more data, or a smaller pilot?"),
        ("I'd rather surface the weak points myself than have them surface later — here's the biggest one.",
         "I'd rather surface the weak points myself than have them surface later — here's the biggest one: our vendor dependency."),
        ("That's a valid concern. Can I take that away and come back with a sharper answer by Friday?",
         "That's a valid concern about staffing. Can I take that away and come back with a sharper answer by Friday?"),
     ]),
    ("De-escalating & finding common ground",
     "A discussion is turning adversarial, and you want to defuse the tension by naming the shared goal.",
     "used to defuse tension in a heated discussion by naming the shared underlying goal",
     [
        ("I think we actually want the same outcome here — we just disagree on the path.",
         "I think we actually want the same outcome here — higher retention — we just disagree on the path to get there."),
        ("Let's find the 80% we agree on before we argue about the 20% we don't.",
         "Let's find the 80% we agree on in this contract before we argue about the 20% we don't."),
        ("Neither of us is wrong here — we're optimizing for different things.",
         "Neither of us is wrong here — we're optimizing for different things, speed versus long-term stability."),
        ("I don't think this needs to be a zero-sum conversation.",
         "I don't think budget allocation needs to be a zero-sum conversation between our two teams."),
        ("Can we agree on the goal first, and debate the method second?",
         "Can we agree on the goal of reducing churn first, and debate the method second?"),
        ("It sounds like we're both trying to protect the same thing, just from different angles.",
         "It sounds like we're both trying to protect the customer relationship, just from different angles."),
     ]),
    ("Closing & gaining commitment",
     "You've made your case in a high-stakes discussion and now need to push the group toward an actual, committed decision.",
     "used to push a high-stakes discussion toward an actual, committed decision",
     [
        ("So it sounds like we're aligned on direction — can we call this decided?",
         "So it sounds like we're aligned on direction — can we call the vendor choice decided?"),
        ("What would you need to see to be comfortable signing off today rather than next week?",
         "What would you need to see to be comfortable signing off on the budget today rather than next week?"),
        ("Let's not let perfect be the enemy of good here — are we comfortable moving forward with 80% confidence?",
         "Let's not let perfect be the enemy of good here — are we comfortable moving forward with 80% confidence on the launch date?"),
        ("If there's no objection in the next thirty seconds, I'll take that as agreement.",
         "If there's no objection in the next thirty seconds, I'll take that as agreement on the new pricing tier."),
        ("Who owns the next step, and by when?",
         "Who owns the next step on the vendor contract, and by when?"),
        ("Can we commit to this as the working plan, with a checkpoint in [timeframe] to revisit if needed?",
         "Can we commit to this as the working plan, with a checkpoint in six weeks to revisit if needed?"),
        ("I want to leave this room with a decision, not just a good discussion.",
         "I want to leave this room with a decision on staffing, not just a good discussion."),
     ]),
]

if __name__ == "__main__":
    generate_topic(
        out_path=OUT_PATH,
        exam_id="persuasion-debate",
        title="Chunk Atlas — Situations: Persuasion & High-Stakes Debate",
        tier_id=TIER_ID,
        tier_name=TIER_NAME,
        groups_def=groups_def,
    )
