import os
import sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, SCRIPT_DIR)
from lib import generate_topic

OUT_PATH = os.path.join(SCRIPT_DIR, "..", "data", "presentations-demos.json")

# Phrase content below is copied by hand (lightly cleaned up: casual
# contractions normalized, UI/ticket-specific jargon trimmed to generic
# equivalents, overly narrow meta-comments dropped) from the
# "Presentations & Demos" topic (tier "core" / nav tab "Situations"),
# sections B1-B9 (presentation/demo delivery functions) plus I1-I6 (a
# vocabulary set for describing data trends when presenting results/KPIs
# in a demo or report — kept and lightly trimmed since the phrases are
# themselves genuine reusable business-English chunks). B5 is split into
# 2 finer sub-groups (deflecting deep questions vs. admitting uncertainty)
# since it bundles two distinct functions, mirroring how
# generate_core_patterns.py split its H14 into finer sub-groups. The I1/I2
# synonym lists are trimmed to a representative subset per intensity band
# rather than every listed synonym, to keep each phrase's example genuinely
# distinct rather than padding with near-duplicates.
TIER_ID = "core"
TIER_NAME = "Situations"

groups_def = [
    ("Opening & framing the talk",
     "You're about to start a presentation or demo and need to open it and state its purpose.",
     "used to open a presentation or demo and state its purpose or agenda",
     [
        ("Welcome to the session.",
         "Welcome to the session — thanks everyone for making time this afternoon."),
        ("How are you all?",
         "How are you all? Hope the Monday didn't hit too hard."),
        ("It's my pleasure to be here today.",
         "It's my pleasure to be here today to walk you through the new checkout flow."),
        ("Thank you for giving me the opportunity to present this issue.",
         "Thank you for giving me the opportunity to present this issue to the leadership team."),
        ("Let me start by introducing myself.",
         "Let me start by introducing myself — I lead the platform team behind this feature."),
        ("Let me brief you on...",
         "Let me brief you on the changes we shipped to the reporting dashboard this sprint."),
        ("The agenda is about...",
         "The agenda is about the Q3 roadmap and the two features we're prioritizing."),
        ("I'd like to present you with some amazing findings.",
         "I'd like to present you with some amazing findings from last quarter's A/B test."),
        ("The aim of this talk is to update you on...",
         "The aim of this talk is to update you on the migration progress and what's left."),
        ("The bottom line of this talk is to suggest some alternatives...",
         "The bottom line of this talk is to suggest some alternatives to the current pricing model."),
        ("This talk was designed to...",
         "This talk was designed to give the sales team a clear picture of the new features."),
        ("Good afternoon everyone. Today I'll walk you through the key enhancements delivered in this sprint.",
         "Good afternoon everyone. Today I'll walk you through the key enhancements delivered in this sprint, then open it up for questions."),
        ("First, let me give you a quick context on this enhancement.",
         "First, let me give you a quick context on this enhancement — previously, users had no way to bulk-edit tasks."),
        ("Our solution is to use...",
         "Our solution is to use a queue so requests don't time out during peak hours."),
     ]),
    ("Signposting & structuring a talk",
     "You want to signal to the audience how your presentation is structured as you move through it.",
     "used to signal how a presentation is structured while moving through it",
     [
        ("So first things first, ...",
         "So first things first, let's look at where the numbers stood at the start of the quarter."),
        ("My first point is on...",
         "My first point is on adoption — only 12% of users found this feature on their own."),
        ("Before moving to the second point, I'd like to emphasize that...",
         "Before moving to the second point, I'd like to emphasize that this fix is already live in production."),
        ("First... second... third...",
         "First, the problem. Second, our approach. Third, the results so far."),
        ("Let's start by...",
         "Let's start by looking at where the current flow breaks down."),
        ("To give you some background,...",
         "To give you some background, this project started as a response to rising support tickets."),
        ("One possible explanation is...",
         "One possible explanation is that the new onboarding steps confused first-time users."),
        ("As you can see...",
         "As you can see on this slide, sign-ups dipped right after the pricing change."),
        ("The key here is...",
         "The key here is that the fix only took two lines of code, but it took weeks to diagnose."),
        ("Let's revisit that point from earlier...",
         "Let's revisit that point from earlier about the mobile drop-off rate."),
     ]),
    ("Explaining before vs. after / what changed",
     "You're demoing a new feature and need to contrast the old behavior with the new one.",
     "used to contrast old behavior with new behavior when demoing a change",
     [
        ("Previously...",
         "Previously, users had to refresh the page manually to see updated status."),
        ("Prior to this release...",
         "Prior to this release, the export only supported CSV, not Excel."),
        ("Going forward...",
         "Going forward, all new accounts will default to the simplified onboarding flow."),
        ("Coming back to the original requirement...",
         "Coming back to the original requirement, the client asked for a single approval step, not two."),
        ("Instead of a single \"Create a task\" button, we now have two: the buttons remain deactivated until all required fields are populated.",
         "Instead of a single \"Create a task\" button, we now have two: Save Draft and Submit — both stay deactivated until all required fields are populated."),
        ("The old behaviour was..., and the new behaviour is...",
         "The old behaviour was silently failing on invalid input, and the new behaviour is showing an inline error message."),
        ("You will notice a clear difference between the old flow and the updated flow.",
         "You will notice a clear difference between the old flow and the updated flow, especially at the payment step."),
        ("This new endpoint will perform calculations in the back to validate the data.",
         "This new endpoint will perform calculations in the back to validate the data before the order is confirmed."),
        ("This allows users to...",
         "This allows users to bulk-edit up to fifty tasks at once instead of one at a time."),
        ("We've introduced...",
         "We've introduced a retry mechanism so failed uploads no longer need to be restarted from scratch."),
        ("This reduces confusion for end users because...",
         "This reduces confusion for end users because the status label now matches the color of the icon."),
        ("The flow is now more intuitive as users can...",
         "The flow is now more intuitive as users can see their saved progress without leaving the page."),
     ]),
    ("Directing attention & highlighting",
     "You're demoing something on screen and want to point the audience's attention to a specific detail.",
     "used to point the audience's attention to a specific detail on screen during a demo",
     [
        ("Take a look at the icon next to the Stage field.",
         "Take a look at the icon next to the Stage field — that's the new bulk-edit shortcut."),
        ("Notice how these buttons remain grayed out (disabled) until...",
         "Notice how these buttons remain grayed out (disabled) until all required fields are filled in."),
        ("If you look closely at the status labels, you'll see...",
         "If you look closely at the status labels, you'll see they now update in real time."),
        ("What's important here is that...",
         "What's important here is that the change only applies to new orders, not existing ones."),
        ("Please focus on this section here...",
         "Please focus on this section here — this is the part that changed the most."),
        ("Let me draw your attention to this element...",
         "Let me draw your attention to this element — the new progress bar at the top."),
        ("Pay attention to the behaviour when I click here.",
         "Pay attention to the behaviour when I click here — the form auto-saves without a page reload."),
        ("Behind the scenes, the API is now filtering...",
         "Behind the scenes, the API is now filtering out cancelled orders before they hit the dashboard."),
        ("The system intelligently hides the edit option once the task is Approved.",
         "The system intelligently hides the edit option once the task is Approved, to prevent accidental changes."),
        ("This is the crucial update for this feature.",
         "This is the crucial update for this feature — it's what actually fixes the sync issue."),
     ]),
    ("Handling tough or deep questions",
     "You've been asked a question that goes far deeper than the intended scope of your talk.",
     "used to deflect or park a question that goes deeper than the scope of the current talk",
     [
        ("For today, I intentionally want to keep things at high-level.",
         "For today, I intentionally want to keep things at high-level — happy to go deeper afterward."),
        ("Good question — that's getting pretty deep.",
         "Good question — that's getting pretty deep into the architecture, more than we have time for today."),
        ("I'm focusing on the big picture here.",
         "I'm focusing on the big picture here rather than the exact implementation details."),
        ("Let me pause for a second and reframe this.",
         "Let me pause for a second and reframe this — the real question is about reliability, not speed."),
        ("The main idea here is...",
         "The main idea here is that we're trading a bit of latency for a lot more consistency."),
        ("Let me put it another way.",
         "Let me put it another way: think of it as a safety net, not a bottleneck."),
        ("You're absolutely right — at a deeper level, it's way more complicated than this. For this session, I'm simplifying on purpose to keep the core idea clear.",
         "You're absolutely right — at a deeper level, the retry logic is way more complicated than this. For this session, I'm simplifying on purpose to keep the core idea clear."),
        ("That's a really interesting angle. To keep us on time, let me park this for now.",
         "That's a really interesting angle on pricing. To keep us on time, let me park this for now and follow up after."),
        ("Let me zoom out for a second.",
         "Let me zoom out for a second before we go further into the edge cases."),
        ("I'll summarize this in one sentence.",
         "I'll summarize this in one sentence: fewer clicks, faster checkout."),
        ("You're right that there's more nuance — that's a good sign the model is landing.",
         "You're right that there's more nuance to the pricing logic than this slide shows — that's a good sign the model is landing."),
        ("That's helpful — let me pause you there so we can hear other views.",
         "That's helpful — let me pause you there so we can hear other views before we go deeper."),
     ]),
    ("Admitting uncertainty & following up",
     "You're asked a question mid-demo that you can't answer accurately on the spot.",
     "used to admit you don't know an answer on the spot and commit to following up",
     [
        ("That's a very good question — let me pull up an example to explain further. Hang on a sec.",
         "That's a very good question — let me pull up an example to explain further. Hang on a sec while I find the right screen."),
        ("I don't want to guess and give you a wrong answer. Let me take this offline and get back to you after this session.",
         "I don't want to guess and give you a wrong answer on the pricing edge case. Let me take this offline and get back to you after this session."),
        ("I don't have the exact answer off the top of my head.",
         "I don't have the exact number off the top of my head, but I'll confirm it by email."),
        ("I don't have a correct answer right now, but I know where this sits.",
         "I don't have a correct answer right now, but I know where this sits in the backlog — I'll check the ticket."),
        ("Let me check the details and get back to you.",
         "Let me check the details on the rollout timeline and get back to you tomorrow."),
     ]),
    ("Handling interruptions",
     "Someone interrupts your demo with a question or comment mid-flow, and you need to acknowledge it without losing your place.",
     "used to acknowledge an interruption during a demo without losing your train of thought",
     [
        ("That's a great point, let me finish this flow first, then we'll come back to it.",
         "That's a great point about permissions, let me finish this flow first, then we'll come back to it."),
        ("This part is still in progress — what you're seeing is an early version, and we're planning to improve it next.",
         "This part is still in progress — what you're seeing is an early version of the dashboard, and we're planning to improve the filters next."),
        ("Can anyone help to explain?",
         "I don't have the exact context on that ticket — can anyone help to explain?"),
        ("I'll call on a few of you to share your thoughts — don't be shy, we're here to learn together.",
         "I'll call on a few of you to share your thoughts on this once I finish the walkthrough — don't be shy, we're here to learn together."),
     ]),
    ("Technical failure recovery",
     "Your demo environment glitches or fails mid-presentation and you need to recover smoothly.",
     "used to recover smoothly when a demo environment glitches or fails mid-presentation",
     [
        ("Looks like this environment is a bit unstable — let me quickly show the expected behavior.",
         "Looks like this environment is a bit unstable — let me quickly show the expected behavior using yesterday's recording."),
        ("It looks like the environment isn't responding at the moment. The change itself has been implemented, so I'll explain the expected behaviour.",
         "It looks like the staging environment isn't responding at the moment. The change itself has been implemented, so I'll explain the expected behaviour instead."),
        ("Since this isn't loading, I'll switch to screenshots for this example.",
         "Since this isn't loading, I'll switch to screenshots for this example of the export flow."),
        ("One moment while I open that endpoint.",
         "One moment while I open that endpoint in Postman to show the response."),
        ("Let me navigate there.",
         "Let me navigate there — one second, it's under Settings."),
        ("Let me show that again.",
         "Let me show that again, I don't think the screen share caught it the first time."),
        ("We've tested this, and normally it works like this...",
         "We've tested this, and normally it works like this — the confirmation email arrives within a minute."),
        ("This might be an environment issue.",
         "This might be an environment issue with staging, not a bug in the code itself."),
        ("Let me update the application first. Now I'll retrieve it again — and here we can see the new fields in the response.",
         "Let me update the application first. Now I'll retrieve it again — and here we can see the new fields in the response, exactly as expected."),
     ]),
    ("Summarizing & closing a presentation",
     "You're wrapping up your presentation and want to recap the main points before moving to Q&A.",
     "used to recap the main points of a presentation before closing or moving to Q&A",
     [
        ("So, to summarize this section...",
         "So, to summarize this section, adoption is up but retention still needs work."),
        ("The main takeaway is...",
         "The main takeaway is that the new flow cut support tickets by almost a third."),
        ("That completes the API changes.",
         "That completes the API changes — the new endpoints are already live in staging."),
        ("That wraps up the response model enhancements.",
         "That wraps up the response model enhancements for this sprint."),
        ("Let me run over the key points again.",
         "Let me run over the key points again before we move to questions."),
        ("I'd like to leave you with some thoughts.",
         "I'd like to leave you with some thoughts on where this feature could go next."),
        ("Let me close now with a story that summarizes my talk. Thank you for coming.",
         "Let me close now with a story that summarizes my talk. Thank you for coming, everyone."),
        ("That's our idea — now let's move to Q&A — please feel free to ask any questions!",
         "That's our idea for the new dashboard — now let's move to Q&A — please feel free to ask any questions!"),
        ("Any questions before we move on?",
         "Any questions before we move on to the next feature?"),
        ("With this improvement, the average time to create an order is reduced from around 5 minutes to about 1 minute.",
         "With this improvement, the average time to create an order is reduced from around 5 minutes to about 1 minute — a big win for the sales team."),
     ]),
    ("Transitions & replacing filler words",
     "You're moving from one point of your presentation to the next and want a clean, professional transition.",
     "used to transition cleanly between points in a presentation instead of using filler words",
     [
        ("Moving on to...",
         "Moving on to the second feature we shipped this sprint."),
        ("Next, let's look at...",
         "Next, let's look at how this affects the mobile app specifically."),
        ("The next change relates to...",
         "The next change relates to how refunds are processed."),
        ("Now that we've seen X, let's move to Y.",
         "Now that we've seen the new dashboard, let's move to how alerts are configured."),
        ("In this case...",
         "In this case, the fallback kicks in automatically after three failed retries."),
        ("More specifically...",
         "More specifically, this only affects accounts on the legacy pricing plan."),
        ("For example...",
         "For example, our largest customer cut their processing time in half using this feature."),
        ("Let's look at...",
         "Let's look at how the new filters actually behave with a real dataset."),
     ]),
    ("Describing an increase",
     "You're presenting a chart and need the right verb to describe a metric going up.",
     "used to describe a metric or figure going up, at varying degrees of intensity",
     [
        ("edged up",
         "Revenue edged up slightly in March, from $2.1M to $2.15M."),
        ("rose",
         "Active users rose from 40,000 to 46,000 over the quarter."),
        ("climbed",
         "Customer satisfaction climbed steadily after the support team was expanded."),
        ("increased",
         "Average order value increased by 8% after the bundling change."),
        ("surged",
         "Sign-ups surged after the feature was mentioned in a major tech newsletter."),
        ("jumped",
         "Traffic jumped 40% the week the campaign launched."),
        ("soared",
         "Demand soared during the holiday season, well past our forecast."),
        ("skyrocketed",
         "Support tickets skyrocketed after the outage, from 30 a day to over 300."),
     ]),
    ("Describing a decrease",
     "You're presenting a chart and need the right verb to describe a metric going down.",
     "used to describe a metric or figure going down, at varying degrees of intensity",
     [
        ("edged down",
         "Churn edged down slightly this quarter, from 4.2% to 4.0%."),
        ("fell",
         "Page load time fell from 3.2 seconds to 1.8 seconds after the CDN change."),
        ("declined",
         "New sign-ups declined in July, likely due to the seasonal slowdown."),
        ("dropped",
         "Cart abandonment dropped after we simplified the checkout form."),
        ("plunged",
         "Conversion plunged the day the payment gateway went down."),
        ("slumped",
         "Ad click-through rates slumped after the platform changed its algorithm."),
        ("tumbled",
         "The stock tumbled after the earnings miss was announced."),
        ("collapsed",
         "Engagement collapsed after the redesign confused long-time users."),
     ]),
    ("Describing stability",
     "You're presenting a chart and need to describe a metric that hasn't moved much.",
     "used to describe a metric that has stayed roughly the same over a period",
     [
        ("held steady",
         "Retention held steady at around 82% for the third straight quarter."),
        ("remained flat",
         "Pricing remained flat throughout the year despite rising costs."),
        ("stabilized",
         "Server response times stabilized once the new caching layer went live."),
        ("plateaued",
         "Growth plateaued after the initial launch spike, as expected."),
     ]),
    ("Describing volatility",
     "You're presenting a chart and need to describe a metric that's been jumping around unpredictably.",
     "used to describe a metric that has fluctuated unpredictably over a period",
     [
        ("fluctuated",
         "Daily active users fluctuated a lot during the beta, depending on the day of the week."),
        ("was volatile",
         "Ad spend efficiency was volatile in Q1 as we tested different channels."),
        ("whipsawed",
         "Conversion whipsawed between the two test variants before settling down."),
        ("swung between X and Y",
         "Response times swung between 200ms and 900ms before we found the bottleneck."),
     ]),
    ("Describing the size or speed of a change",
     "You're presenting data and need an adverb to describe how large or sudden a change was.",
     "used as an adverb to describe how large, small, or sudden a change in the data was",
     [
        ("significantly",
         "Support response time improved significantly after we added a second shift."),
        ("substantially",
         "The new pricing substantially reduced churn among small business customers."),
        ("marginally",
         "The redesign only marginally improved conversion, from 3.1% to 3.3%."),
        ("slightly",
         "Load time increased slightly after we added the new tracking script."),
        ("moderately",
         "Engagement grew moderately after the onboarding tweak, nothing dramatic."),
        ("steadily",
         "Revenue grew steadily throughout the year, without any big spikes."),
        ("gradually",
         "Adoption increased gradually as more teams migrated to the new tool."),
        ("sharply",
         "Costs rose sharply after the vendor changed their pricing tier."),
        ("dramatically",
         "Signups dropped dramatically the day the free tier was removed."),
     ]),
    ("Comparisons & benchmarking",
     "You're presenting results and need to compare a figure against a benchmark, forecast, or competitor.",
     "used to compare a figure against a benchmark, forecast, or competitor when presenting results",
     [
        ("compared to",
         "Revenue this quarter was up 15% compared to the same period last year."),
        ("relative to",
         "Our churn rate is low relative to the industry average."),
        ("in line with expectations",
         "Q2 revenue came in in line with expectations, right around $4M."),
        ("outperformed the sector",
         "Our retention outperformed the sector average by nearly ten points."),
        ("underperformed peers",
         "Mobile conversion underperformed peers this quarter, and that's our next focus area."),
        ("came in above forecasts",
         "Sign-ups came in above forecasts for the third month running."),
        ("came in below forecasts",
         "Revenue came in below forecasts, mostly due to the delayed enterprise deal."),
        ("widened the gap with",
         "We widened the gap with our closest competitor on page load speed."),
        ("on a year-on-year (YoY) basis",
         "Revenue is up 22% on a year-on-year (YoY) basis."),
        ("hit a record high",
         "Daily active users hit a record high the week we launched the mobile app."),
     ]),
    ("Forecasting & outlook language",
     "You're presenting projections and need language to talk about what's likely to happen next.",
     "used to talk about projections, likelihood, and outlook when presenting future results",
     [
        ("is expected to",
         "Revenue is expected to reach $5M by the end of the fiscal year."),
        ("is likely to",
         "Churn is likely to rise slightly once the promotional pricing ends."),
        ("is poised to",
         "The new market segment is poised to become our biggest growth driver."),
        ("could potentially",
         "This change could potentially double our conversion rate if the test holds up."),
        ("there is a risk that",
         "There is a risk that demand won't scale as fast as our current infrastructure."),
        ("remains to be seen whether",
         "It remains to be seen whether this trend holds once the holiday season ends."),
        ("the outlook remains cautious",
         "Given the supply chain delays, the outlook remains cautious for next quarter."),
        ("the outlook remains positive",
         "Despite the slow start, the outlook remains positive heading into Q4."),
        ("downside risk",
         "The main downside risk is that our biggest customer renews at a lower tier."),
        ("upside potential",
         "There's real upside potential if the new region performs like our pilot market."),
     ]),
    ("Explaining cause vs. correlation",
     "You're presenting data and need to explain why something happened, or flag when it's only a correlation.",
     "used to explain why something happened in the data, or to flag correlation rather than proven causation",
     [
        ("driven by",
         "The revenue jump was largely driven by the new enterprise tier."),
        ("fueled by",
         "Growth this quarter was fueled by the referral program we launched in April."),
        ("attributable to",
         "Most of the improvement is attributable to the redesigned onboarding flow."),
        ("can be traced back to",
         "The drop in retention can be traced back to the pricing change in May."),
        ("correlates with",
         "Higher support response time correlates with lower renewal rates."),
        ("correlation does not necessarily imply causation",
         "The two metrics move together, but correlation does not necessarily imply causation here."),
        ("this coincided with",
         "The traffic spike coincided with the newsletter feature, though we can't confirm it caused it."),
        ("a contributing factor was",
         "A contributing factor was likely the seasonal dip we see every August."),
     ]),
    ("Hedging in data analysis",
     "You're presenting an analysis and want to soften a claim rather than stating it as an absolute fact.",
     "used to soften a claim rather than stating it as an absolute fact when presenting an analysis",
     [
        ("the data suggests",
         "The data suggests users are dropping off at the payment step, not the sign-up step."),
        ("the data indicates",
         "The data indicates a strong preference for the annual plan over monthly."),
        ("on balance",
         "On balance, the pilot results support rolling this out to the rest of the team."),
        ("all things considered",
         "All things considered, the migration went more smoothly than we expected."),
        ("it is worth noting that",
         "It is worth noting that this sample only covers our EU customers."),
        ("one caveat is that",
         "One caveat is that this data doesn't include the accounts we onboarded last week."),
        ("assuming [X] holds true",
         "Assuming current demand holds true, we'll need to add capacity by Q3."),
        ("based on available data",
         "Based on available data, the new pricing hasn't hurt conversion so far."),
     ]),
]

if __name__ == "__main__":
    generate_topic(
        out_path=OUT_PATH,
        exam_id="presentations-demos",
        title="Chunk Atlas — Situations: Presentations & Demos",
        tier_id=TIER_ID,
        tier_name=TIER_NAME,
        groups_def=groups_def,
    )
