import os
import sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, SCRIPT_DIR)
from lib import generate_topic

OUT_PATH = os.path.join(SCRIPT_DIR, "..", "data", "idiomaticity.json")

# Phrase content copied by hand from the "Idiomaticity: Phrasal Verbs,
# Binomials, Idioms" topic (tier "mastery" / nav tab "Language Systems") —
# sections M6.1-M6.7 (+L6.6/L6.7 continuation). "c" (comparison) and "n"
# (note) items are skipped per spec. Long unlabeled comma-lists (M6.1,
# M6.3, M6.5) are split into finer groups mirroring the source's own
# sub-themes; already-labeled sub-lists (Du an/Trao doi/... in M6.2, M6.4,
# M6.6, M6.7) map 1:1 to groups. A handful of items repeat verbatim across
# two source headers (e.g. "touch base", "bottleneck", "run out of",
# "kick off", "put off", "bring forward", "sort out", "iron out", "work
# out", "figure out", "find out", "look into", "put up with", "get
# across", "bring up", "point out", "run by", "take off", "wind down") —
# each is kept once, at its first/clearest occurrence, and dropped from
# the later duplicate group.
TIER_ID = "mastery"
TIER_NAME = "Language Systems"

groups_def = [
    ("Coping, waiting & catching up phrasal verbs",
     "You want to describe generating an idea, tolerating something, evading consequences, or catching up on a backlog, using an everyday phrasal verb instead of a stiff formal verb.",
     "an everyday phrasal verb for coping with, evading, or catching up on something, not a formal Latinate verb",
     [
        ("come up with", "The team came up with a clever workaround overnight."),
        ("put up with", "I don't know how support puts up with that many duplicate tickets."),
        ("get away with", "He got away with missing the deadline because nobody escalated it."),
        ("look forward to", "I'm really looking forward to seeing the new dashboard live."),
        ("run out of", "We ran out of time before we could test the edge cases."),
        ("catch up on", "I spent the weekend catching up on a month of unread tickets."),
        ("get round to", "I never got round to reviewing that PR properly."),
     ]),
    ("Figuring things out & outcomes phrasal verbs",
     "You want to describe understanding, resolving, discovering, or reaching an outcome, using an everyday phrasal verb instead of a formal single-word verb.",
     "an everyday phrasal verb for figuring something out, discovering it, or describing how it turned out",
     [
        ("figure out", "It took us an hour to figure out why the build was failing."),
        ("sort out", "Can you sort out the invoice mix-up with finance?"),
        ("work out", "We worked out a compromise that both teams could live with."),
        ("turn out", "The pilot turned out better than any of us expected."),
        ("find out", "We only found out about the price change from a customer complaint."),
        ("point out", "She pointed out that the numbers didn't match the earlier report."),
        ("bring up", "He brought up the budget issue right at the end of the call."),
        ("come across", "I came across an old ticket that explains exactly this bug."),
        ("end up", "We ended up rebuilding the whole flow from scratch."),
     ]),
    ("Handling tasks & objects phrasal verbs",
     "You want to describe investigating, reviewing, or physically handling a task or item, using an everyday phrasal verb.",
     "an everyday phrasal verb for investigating, reviewing, or physically handling something",
     [
        ("look into", "I'll look into why the export feature keeps timing out."),
        ("deal with", "Can you deal with the vendor email while I'm in this call?"),
        ("go through", "Let's go through the contract clause by clause."),
        ("go over", "We should go over the deck once more before the client sees it."),
        ("run by", "Let me run this pricing idea by the finance team first."),
        ("check in", "I'll check in with the client once the fix is deployed."),
        ("drop off", "Can you drop off the signed contract at reception?"),
        ("pick up", "I'll pick up your part of the deck if you're still stuck on the demo."),
        ("hold off", "Let's hold off on announcing this until legal confirms the wording."),
     ]),
    ("Project-lifecycle phrasal verbs",
     "You want to describe a stage in a project's lifecycle — starting, scaling, reducing, or finishing it — using an everyday phrasal verb.",
     "an everyday phrasal verb describing a stage in a project's lifecycle, from starting to winding down",
     [
        ("kick off", "We kick off the new sprint on Monday."),
        ("roll out", "We're rolling out the update to 10% of users first."),
        ("scale back", "We had to scale back the launch after the vendor delay."),
        ("scale up", "Once the pilot works, we'll scale up to the whole region."),
        ("ramp up", "Support is ramping up staffing ahead of the holiday rush."),
        ("wind down", "The old platform will wind down over the next two months."),
        ("phase out", "We're phasing out the legacy API by the end of the year."),
        ("carry out", "The vendor carried out the migration over the weekend."),
        ("follow through", "It's a good plan, we just need to follow through on it."),
     ]),
    ("Communication & follow-up phrasal verbs",
     "You want to describe following up, checking in, or including someone in a conversation, using an everyday workplace phrasal verb.",
     "an everyday workplace phrasal verb for following up, checking in, or including someone",
     [
        ("follow up", "I'll follow up with the client tomorrow if we haven't heard back."),
        ("touch base", "Let's touch base after the demo to see how it landed."),
        ("loop in", "Can you loop in legal before we send this out?"),
        ("circle back", "We can circle back to pricing once the roadmap's settled."),
        ("sync up", "The two teams need to sync up before the joint release."),
        ("run something by someone", "I want to run this by you before I send it to the client."),
        ("flag up", "She flagged up a risk in the contract terms early on."),
        ("chase up", "I'll chase up the vendor, they still owe us the final invoice."),
     ]),
    ("Problem-handling phrasal verbs",
     "You want to describe resolving, avoiding, or reacting to a problem, using an everyday workplace phrasal verb.",
     "an everyday workplace phrasal verb for resolving, avoiding, or reacting to a problem",
     [
        ("iron out", "We still need to iron out a few details in the contract."),
        ("smooth over", "She smoothed things over with the client after the missed call."),
        ("head off", "We caught the bug early enough to head off any real damage."),
        ("back down", "The vendor finally backed down on the price increase."),
        ("push back", "Engineering pushed back on the deadline, and they were right to."),
        ("call off", "We had to call off the demo when the staging server went down."),
        ("put off", "Let's not put off this conversation any longer."),
        ("hold up", "The whole release was held up by one failing test."),
        ("fall through", "The partnership fell through at the last minute."),
     ]),
    ("Decision-making phrasal verbs",
     "You want to describe narrowing down, weighing, or finalizing a decision, using an everyday workplace phrasal verb.",
     "an everyday workplace phrasal verb for narrowing down, weighing, or finalizing a decision",
     [
        ("rule out", "We've ruled out the cheaper vendor over reliability concerns."),
        ("narrow down", "Let's narrow down the options to two before the client call."),
        ("weigh up", "We need to weigh up the cost against the time saved."),
        ("sign off (on)", "Finance still needs to sign off on the new budget."),
        ("go ahead with", "The client wants to go ahead with the original proposal."),
        ("opt for", "We opted for the simpler design over the flashier one."),
        ("settle on", "We finally settled on a launch date of March 3rd."),
        ("bring forward", "Can we bring the review meeting forward to Wednesday?"),
     ]),
    ("Binomials: pace & degree",
     "You want to describe pace, degree, or approximation using a fixed two-word binomial expression, in the exact word order native speakers always use.",
     "a fixed binomial expression, in a set word order that native speakers never reverse, describing pace or degree",
     [
        ("back and forth", "We went back and forth on the pricing for almost a week."),
        ("by and large", "By and large, the migration went smoothly."),
        ("sooner or later", "Sooner or later, someone was going to notice the discrepancy."),
        ("give or take", "The fix will take a day, give or take."),
        ("more or less", "The two proposals are more or less the same in cost."),
        ("sink or swim", "We threw the new hire straight onto the client call — sink or swim."),
     ]),
    ("Binomials: overview expressions",
     "You want to give an overview of something's details, tradeoffs, or status, using a fixed binomial expression.",
     "a fixed binomial expression, in a set word order, used to give an overview of something's details or status",
     [
        ("the ins and outs", "She knows the ins and outs of the billing system better than anyone."),
        ("the pros and cons", "Let's weigh the pros and cons before committing to the vendor."),
        ("bits and pieces", "There are still a few bits and pieces left to finish before launch."),
        ("tried and tested", "We're sticking with the tried and tested onboarding flow for now."),
        ("up and running", "The new server is finally up and running."),
        ("cut and dried", "The contract terms aren't as cut and dried as we'd like."),
     ]),
    ("Binomials: everyday frequency & condition",
     "You want to describe frequency, readiness, or condition using a fixed binomial expression.",
     "a fixed binomial expression, in a set word order, describing frequency, readiness, or condition",
     [
        ("here and there", "We made a few tweaks here and there before shipping."),
        ("now and then", "The old bug still shows up now and then."),
        ("part and parcel", "Handling angry customers is part and parcel of the job."),
        ("ready and willing", "The new hires are ready and willing to take on the migration."),
        ("safe and sound", "The backup arrived safe and sound before the deadline."),
        ("first and foremost", "First and foremost, we need to stop the data from leaking further."),
     ]),
    ("Binomials: workplace",
     "You want to describe a business concept using a fixed workplace binomial expression.",
     "a fixed workplace binomial expression, in a set word order, describing a standard business concept",
     [
        ("time and effort", "It took a lot of time and effort to get the two systems talking to each other."),
        ("terms and conditions", "Make sure legal reviews the terms and conditions before we publish them."),
        ("profit and loss", "The profit and loss statement shows Q2 was actually break-even."),
        ("supply and demand", "Pricing here is really just supply and demand — we raise it when we're full."),
        ("trial and error", "We got the onboarding flow right mostly through trial and error."),
        ("rules and regulations", "The new market has stricter rules and regulations around data storage."),
        ("all things considered", "All things considered, the launch went better than we feared."),
     ]),
    ("Workplace idioms: naming a problem",
     "You want to name a difficult or awkward problem vividly, using a workplace idiom instead of a flat word like 'issue'.",
     "a workplace idiom for naming a difficult, awkward, or unresolved problem",
     [
        ("the elephant in the room", "Nobody wanted to mention the elephant in the room: the budget cut."),
        ("a can of worms", "Changing the pricing model opened up a whole can of worms."),
        ("a double-edged sword", "Automating support is a double-edged sword — faster, but less personal."),
        ("a stopgap", "This fix is just a stopgap until we rebuild the module properly."),
        ("a moving target", "The requirements have been a moving target since day one."),
        ("a bottleneck", "Manual approval has become a real bottleneck in the release process."),
     ]),
    ("Workplace idioms: progress",
     "You want to describe project progress vividly, using a workplace idiom instead of a plain phrase like 'making progress'.",
     "a workplace idiom describing how a project is progressing, from starting out to stalling",
     [
        ("move the needle", "None of these small fixes are going to move the needle on churn."),
        ("get the ball rolling", "Let's get the ball rolling on the contract this week."),
        ("gain momentum", "The campaign really started to gain momentum after the first week."),
        ("hit the ground running", "The new lead hit the ground running on day one."),
        ("back to the drawing board", "The client rejected the design, so it's back to the drawing board."),
        ("in the pipeline", "There are two more features in the pipeline for next quarter."),
     ]),
    ("Workplace idioms: decisions & tradeoffs",
     "You want to describe a difficult decision or tradeoff vividly, using a workplace idiom.",
     "a workplace idiom describing a difficult decision, a tradeoff, or getting people aligned",
     [
        ("bite the bullet", "We finally bit the bullet and rewrote the whole billing module."),
        ("cut corners", "We can't cut corners on security just to hit the date."),
        ("play devil's advocate", "Let me play devil's advocate for a second — what if the client says no?"),
        ("on the same page", "Let's make sure everyone's on the same page before we tell the client."),
        ("low-hanging fruit", "Fixing the checkout typo was low-hanging fruit compared to the redesign."),
        ("a judgement call", "Whether to delay the launch is really a judgement call at this point."),
     ]),
    ("Workplace idioms: rough estimation",
     "You want to give a rough estimate or high-level summary vividly, using a workplace idiom instead of saying 'approximately'.",
     "a workplace idiom for giving a rough estimate or a high-level summary rather than exact detail",
     [
        ("a ballpark figure", "Can you give me a ballpark figure before the official quote comes in?"),
        ("boil down to", "The whole disagreement boils down to who owns the final sign-off."),
        ("in broad strokes", "Let me explain the plan in broad strokes before we get into detail."),
        ("a rule of thumb", "As a rule of thumb, we budget an extra week for QA."),
        ("at a high level", "At a high level, the new architecture separates billing from the core app."),
     ]),
    ("Workplace idioms: general business praise",
     "You want to praise a business result or idea vividly, using a workplace idiom instead of a flat word like 'good'.",
     "a workplace idiom used to praise a strong result, idea, or advantage",
     [
        ("raise the bar", "This release really raised the bar for what customers expect from us."),
        ("think outside the box", "The intern thought outside the box and suggested skipping the form entirely."),
        ("a game changer", "The new caching layer was a game changer for load times."),
        ("ahead of the curve", "Adopting this framework early put us ahead of the curve."),
        ("a win-win", "Extending the trial period was a win-win for both sides."),
     ]),
    ("Metaphor: ARGUMENT IS WAR",
     "You want to talk about a debate or disagreement using vivid war-like language instead of neutral words like 'discuss' or 'disagree'.",
     "a vivid ARGUMENT IS WAR metaphor for debating or disagreeing, not a neutral discussion verb",
     [
        ("defend a proposal", "You'll need to defend the proposal when finance pushes back on the budget."),
        ("attack a proposal", "Two board members attacked the proposal before we'd even finished presenting it."),
        ("shoot down a proposal", "They shot down the proposal in the first five minutes of the meeting."),
        ("win a point", "She won the point by citing last quarter's churn numbers."),
        ("an indefensible position", "Once the data came out, our old pricing model was an indefensible position."),
        ("common ground", "We finally found common ground on the rollout timeline, if not the budget."),
     ]),
    ("Metaphor: TIME IS MONEY",
     "You want to talk about time as if it were a limited resource you can spend, save, or waste, the way native speakers naturally do.",
     "a vivid TIME IS MONEY metaphor for spending, saving, or wasting time as if it were money",
     [
        ("spend time", "We spent two full days debugging something that turned out to be a config typo."),
        ("waste time", "Let's not waste time re-litigating a decision we made last week."),
        ("save time", "Automating the report saves us three hours every Friday."),
        ("budget time", "Budget an extra hour for questions after the demo."),
        ("a costly delay", "The vendor's late delivery turned into a costly delay for the whole launch."),
        ("invest hours", "The team invested hours into a fix that the vendor could have shipped in a day."),
        ("borrowed time", "Honestly, this workaround has been running on borrowed time since March."),
     ]),
    ("Metaphor: IDEAS ARE OBJECTS",
     "You want to talk about an idea as if it were a physical object you can hold, pass around, or unpack, instead of using an abstract verb like 'consider'.",
     "a vivid IDEAS ARE OBJECTS metaphor for handling or communicating an idea as if it were a physical thing",
     [
        ("grasp an idea", "It took the new hires a while to grasp the idea behind our pricing model."),
        ("put forward an idea", "One of the interns put forward an idea that ended up saving us a full sprint."),
        ("toss around an idea", "We tossed around a few ideas before settling on the current design."),
        ("get an idea across", "The diagram helped us get the idea across faster than the slide full of text."),
        ("unpack a concept", "Let's unpack that concept a bit before we move on to implementation."),
        ("a half-baked idea", "I don't want to pitch a half-baked idea to the client without testing it first."),
     ]),
    ("Metaphor: BUSINESS IS A JOURNEY",
     "You want to describe your project's progress as if it were a physical journey, using words like roadmap, milestones, and detour.",
     "a vivid BUSINESS IS A JOURNEY metaphor for describing project progress as if it were travel",
     [
        ("a roadmap", "We shared the product roadmap with the client to set expectations for the year."),
        ("milestones", "We hit every milestone except the final QA sign-off."),
        ("on track", "Despite the scare last week, we're still on track for the March release."),
        ("a detour", "The security review was a necessary detour, even though it cost us two weeks."),
        ("hit a roadblock", "We hit a roadblock when the vendor's API changed without warning."),
        ("the path forward", "The path forward is a phased rollout, starting with our friendliest customers."),
        ("steer", "It's on the PM to steer the project back on schedule after this delay."),
     ]),
    ("Metaphor: ORGANISATIONS ARE MACHINES/BODIES",
     "You want to describe your team or company's capacity using mechanical or body metaphors like bandwidth, friction, or a lean team.",
     "a vivid ORGANISATIONS ARE MACHINES/BODIES metaphor for describing a team or company's capacity",
     [
        ("bandwidth", "We don't have the bandwidth to take on a fourth project this quarter."),
        ("capacity", "Support is already at capacity — one more escalation and something will slip."),
        ("friction", "There's too much friction between sales and product on feature requests."),
        ("healthy margins", "The new pricing gives us much healthier margins than the old plan did."),
        ("a lean team", "We shipped this with a surprisingly lean team — just three engineers."),
     ]),
    ("Phrasal verbs: starting & finishing",
     "You want to describe the start or end of an activity using an everyday phrasal verb instead of a formal single word like 'commence' or 'terminate'.",
     "an everyday phrasal verb marking the start or end of an activity",
     [
        ("set off", "We set off for the client site at six to beat the traffic."),
        ("set up", "Can you set up a call with the vendor for tomorrow morning?"),
        ("take off", "Sales really took off after we simplified the checkout flow."),
        ("wrap up", "Let's wrap up here — we're five minutes over already."),
        ("wind up", "The pilot program wound up early once we hit our target metrics."),
        ("call it a day", "It's past seven, let's call it a day and pick this up tomorrow."),
        ("knock off", "The team usually knocks off around six on Fridays."),
     ]),
    ("Phrasal verbs: continuing & stopping",
     "You want to describe continuing or stopping an activity using an everyday phrasal verb.",
     "an everyday phrasal verb marking continuing or stopping an activity",
     [
        ("carry on", "Carry on without me, I'll catch up on the notes later."),
        ("keep on", "She kept on pushing until legal finally gave a straight answer."),
        ("go on", "Go on, I didn't mean to interrupt."),
        ("hold on", "Hold on, let me pull up the numbers before we decide."),
        ("hang on", "Hang on a second, I think I misread the spreadsheet."),
        ("give up", "Don't give up on the integration yet, we're close."),
        ("pack in", "I think it's time we packed in this approach and tried something else."),
        ("cut out", "We cut out the extra approval step to speed up the process."),
     ]),
    ("Phrasal verbs: understanding & discovering (extra)",
     "You want to describe understanding or noticing something using an everyday phrasal verb.",
     "an everyday phrasal verb for noticing or understanding something",
     [
        ("make out", "I couldn't quite make out what he meant by 'flexible deadline'."),
        ("catch on", "It took the team a while to catch on to the new naming convention."),
        ("pick up on", "She picked up on the tension in the room before anyone said a word."),
        ("look up", "Look up the client's account before you call them back."),
     ]),
    ("Relationships phrasal verbs",
     "You want to describe how two people or teams get along, or don't, using an everyday phrasal verb.",
     "an everyday phrasal verb describing how two people or teams relate to each other",
     [
        ("get on (with)", "The new hire gets on really well with the design team."),
        ("fall out (with)", "The two founders fell out over the direction of the product."),
        ("make up", "They made up after the argument and the project moved forward fine."),
        ("look up to", "Junior engineers really look up to her technical judgment."),
        ("look down on", "He tends to look down on anyone who hasn't coded in production."),
     ]),
    ("Problems arising & resolving phrasal verbs",
     "You want to describe a problem appearing or being resolved using an everyday phrasal verb.",
     "an everyday phrasal verb describing a problem appearing or being resolved",
     [
        ("come up", "A scheduling conflict came up right before the client call."),
        ("crop up", "New edge cases keep cropping up every time we test this."),
        ("blow up", "The pricing complaint blew up on social media over the weekend."),
        ("blow over", "Give it a day, this will blow over once we send the apology email."),
        ("clear up", "Let's clear up the confusion about who owns this ticket."),
        ("patch up", "We patched up the integration just enough to get through the demo."),
     ]),
    ("People coming & going phrasal verbs",
     "You want to describe someone arriving, leaving, or visiting using an everyday phrasal verb.",
     "an everyday phrasal verb describing someone arriving, leaving, or visiting",
     [
        ("turn up", "Half the invitees didn't turn up to the workshop."),
        ("show up", "He showed up ten minutes late to his own product demo."),
        ("drop in", "Feel free to drop in if you're in the area next week."),
        ("pop round", "I'll pop round to the design team's desk to check the mockups."),
        ("drop by", "The CEO dropped by our stand-up unannounced this morning."),
        ("stop by", "Can you stop by IT before the meeting to grab a loaner laptop?"),
        ("head off", "I need to head off early to catch my flight."),
     ]),
    ("Money & belongings phrasal verbs",
     "You want to describe spending, saving, or contributing money or resources using an everyday phrasal verb.",
     "an everyday phrasal verb describing spending, saving, or contributing money or resources",
     [
        ("use up", "We've used up this month's cloud budget already."),
        ("save up", "We're saving up the extra headcount budget for Q4."),
        ("splash out", "The team splashed out on a nicer venue for the offsite this year."),
        ("pay off", "The investment in automated testing really paid off during this release."),
        ("chip in", "Everyone chipped in a few ideas during the brainstorm."),
        ("put by", "We've put by a small contingency fund in case the vendor raises prices."),
     ]),
    ("Mood phrasal verbs",
     "You want to describe someone's emotional state changing using an everyday phrasal verb.",
     "an everyday phrasal verb describing a change in someone's mood",
     [
        ("cheer up", "The good review really cheered the team up after a rough week."),
        ("calm down", "Let's all calm down before we respond to the client."),
        ("chill out", "You can chill out, the backup actually worked."),
        ("perk up", "The whole room perked up once we mentioned the bonus."),
        ("snap out of it", "He was frustrated about the bug, but he snapped out of it once we found the fix."),
     ]),
    ("Work-task phrasal verbs",
     "You want to describe assigning, transferring, or getting through work using an everyday phrasal verb.",
     "an everyday phrasal verb describing assigning, transferring, or getting through work",
     [
        ("take on", "She's taking on the mobile redesign in addition to her current work."),
        ("take over", "I'll take over the client relationship while you're on leave."),
        ("hand over", "Make sure you hand over your open tickets before you go."),
        ("hand in", "The report is due Friday, please hand it in by noon."),
        ("get through", "We managed to get through the whole backlog before the sprint ended."),
        ("catch up", "I need an hour to catch up on emails after the offsite."),
     ]),
    ("Information phrasal verbs",
     "You want to describe communicating information to someone using an everyday phrasal verb.",
     "an everyday phrasal verb describing communicating information to someone",
     [
        ("put across", "He struggled to put his point across without sounding dismissive."),
        ("fill in", "Can you fill me in on what happened while I was out?"),
        ("brief up", "Someone needs to brief up the new hire before the client call."),
     ]),
    ("Everyday idioms: time",
     "You want to describe timing casually, the way a native speaker would in relaxed conversation, using a fixed idiom rather than a plain phrase.",
     "a fixed everyday idiom for talking about timing casually",
     [
        ("in the long run", "It'll cost more now, but it'll pay off in the long run."),
        ("at the end of the day", "At the end of the day, the client just wants it to work."),
        ("sooner rather than later", "We should fix this sooner rather than later, before it affects more users."),
        ("any day now", "The contract should be signed any day now."),
     ]),
    ("Everyday idioms: luck",
     "You want to talk about luck casually, using a fixed idiom rather than a plain statement.",
     "a fixed everyday idiom for talking about luck casually",
     [
        ("touch wood", "We haven't had an outage in months, touch wood."),
        ("fingers crossed", "Fingers crossed the demo goes smoothly this time."),
        ("just my luck", "Just my luck, the server crashed the one day I was on call."),
        ("the luck of the draw", "Getting a supportive manager on your first project is really the luck of the draw."),
     ]),
    ("Everyday idioms: difficulty",
     "You want to describe how difficult something is, using a vivid idiom instead of a plain word like 'hard'.",
     "a vivid everyday idiom describing how difficult something is",
     [
        ("a hard nut to crack", "This legacy codebase is a hard nut to crack."),
        ("easier said than done", "Simplifying the onboarding sounds great, but it's easier said than done."),
        ("a bit of a slog", "Migrating the database was a bit of a slog, but it's finally done."),
        ("an uphill struggle", "Getting sign-off from three departments has been an uphill struggle."),
     ]),
    ("Everyday idioms: ease",
     "You want to describe how easy something is, using a vivid idiom instead of a plain word like 'easy'.",
     "a vivid everyday idiom describing how easy something is",
     [
        ("a piece of cake", "Compared to last quarter's migration, this one's a piece of cake."),
        ("a doddle", "Once you know the shortcut, filing expenses is a doddle."),
        ("plain sailing", "After the first rocky week, the rest of the rollout was plain sailing."),
        ("no sweat", "Adding one more field to the form is no sweat."),
     ]),
    ("Everyday idioms: situations",
     "You want to describe a general situation vividly, using a fixed idiom instead of a plain description.",
     "a vivid everyday idiom describing a general situation",
     [
        ("in the same boat", "Every team missed their Q1 targets, so we're all in the same boat."),
        ("a blessing in disguise", "Losing that client was a blessing in disguise — it freed us up for a bigger deal."),
        ("the last straw", "The third missed deadline was the last straw for the client."),
        ("out of the blue", "The vendor cancelled the contract completely out of the blue."),
     ]),
    ("Everyday idioms: describing people",
     "You want to describe someone's character vividly, using a fixed idiom instead of a plain adjective.",
     "a vivid everyday idiom describing someone's character",
     [
        ("a safe pair of hands", "We put her in charge of the migration because she's a safe pair of hands."),
        ("a live wire", "He's a live wire in meetings — full of energy and ideas."),
        ("down to earth", "The new CEO is surprisingly down to earth for someone at that level."),
        ("full of himself", "He's talented, but he can come across as a bit full of himself."),
        ("hard work", "He's hard work — every small decision turns into a negotiation."),
     ]),
    ("Everyday idioms: giving opinions informally",
     "You want to give a casual, informal opinion using a fixed idiom instead of a plain 'I think'.",
     "a fixed everyday idiom for giving a casual, informal opinion",
     [
        ("to be honest with you", "To be honest with you, I don't think the deadline is realistic."),
        ("if you ask me", "If you ask me, we're overcomplicating the onboarding flow."),
        ("at a guess", "At a guess, I'd say we're about two weeks behind."),
        ("off the record", "Off the record, I don't think the client is happy with the current design."),
     ]),
    ("Everyday idioms: wrapping up",
     "You want to signal that a story or situation is completely finished, using a fixed idiom instead of a plain 'that's finished'.",
     "a fixed everyday idiom for signalling that something is completely finished",
     [
        ("that's that", "We signed the contract, and that's that."),
        ("and there you have it", "We fixed the bug, redeployed, and there you have it."),
        ("job done", "Tests passed, docs updated — job done."),
        ("all's well that ends well", "It was a stressful launch, but all's well that ends well."),
     ]),
]

if __name__ == "__main__":
    generate_topic(
        out_path=OUT_PATH,
        exam_id="idiomaticity",
        title="Chunk Atlas — Language Systems: Idiomaticity",
        tier_id=TIER_ID,
        tier_name=TIER_NAME,
        groups_def=groups_def,
    )
