import os
import sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, SCRIPT_DIR)
from lib import generate_topic

OUT_PATH = os.path.join(SCRIPT_DIR, "..", "data", "everyday-social.json")

# Phrase content below is copied by hand from the "Everyday & Social" topic
# (tier "core" / nav tab "Situations") — sections D1-D18, G1-G2. Register
# here is deliberately casual/social (small talk, storytelling, catching up)
# rather than meeting-room language.
#
# D13 ("Golden chunks") bundles two distinct functions — idiomatic action/
# feeling chunks vs. narrative "twist" templates — split into D13a/D13b,
# mirroring how generate_core_patterns.py split H14.
# D18 ("Ultimate storytelling formula") is skipped: it's a meta recap that
# just re-labels chunks already covered in D1/D4/D6/D12, not new content
# (same kind of exception as H15 in Core Patterns).
# M-equivalent pronunciation tips don't exist in this topic's D/G range.
# G1/G2 items bundle a short scenario description with one or two quoted
# reply lines in a single "m" string; only the quoted English reply lines
# were extracted as chunks, and one pure-instruction line in G2 ("Ask if
# they know how to make it the Vietnamese way.") was skipped since it isn't
# itself a quotable line — it's an instruction to the learner, not a chunk.
TIER_ID = "core"
TIER_NAME = "Situations"

groups_def = [
    ("Storytelling Openers",
     "You're about to tell a friend or coworker a story from your day and need a natural way to kick it off.",
     "used to kick off a casual story, before the details come out",
     [
        ("So basically...", "So basically, I woke up late and missed the whole first hour of the workshop."),
        ("It all started when...", "It all started when I offered to walk my neighbor's dog for the weekend."),
        ("At first, I thought...", "At first, I thought it was just a typo in the invitation."),
        ("At the time, it seemed like a good idea.", "Booking the 6am flight? At the time, it seemed like a good idea."),
        ("I honestly didn't think much of it.", "I honestly didn't think much of it when the barista wrote the wrong name on my cup."),
        ("Everything was going fine until...", "Everything was going fine until the power went out mid-cook."),
        ("That's when things got weird.", "That's when things got weird — my phone just kept ringing with no one there."),
        ("Little did I know...", "Little did I know the 'quick errand' would eat up my whole Saturday."),
     ]),
    ("Narrating Things Going Wrong",
     "You're telling someone about a plan that fell apart and want to mark the point where it started going wrong.",
     "used to mark the point in a casual story where things started going wrong",
     [
        ("Things went downhill fast.", "Things went downhill fast once we realized we'd booked the wrong hotel."),
        ("That's where everything fell apart.", "That's where everything fell apart — the printer jammed right before the party started."),
        ("Needless to say, it was a disaster.", "Needless to say, it was a disaster — three people showed up to the same potluck with lasagna."),
        ("That was a huge mistake.", "Letting my cousin plan the road trip? That was a huge mistake."),
        ("It backfired instantly.", "I tried to surprise her with breakfast in bed — it backfired instantly when the smoke alarm went off."),
        ("I should've seen that coming.", "I should've seen that coming — the dog always chews shoes left by the door."),
        ("One thing led to another...", "One thing led to another, and suddenly we were karaoke-ing at midnight."),
        ("Before I knew it...", "Before I knew it, I'd agreed to host Thanksgiving for fifteen people."),
        ("Somehow, things got even worse.", "I tried to fix the leaky faucet myself, and somehow, things got even worse."),
     ]),
    ("Describing Awkward or Embarrassing Moments",
     "You're describing an embarrassing moment to a friend and want to capture how uncomfortable it felt.",
     "used to describe how uncomfortable or embarrassed you felt in a moment",
     [
        ("I wanted to disappear.", "I called my boss 'mom' by accident on the call — I wanted to disappear."),
        ("It was painfully awkward.", "The silence after my joke fell flat — it was painfully awkward."),
        ("I completely embarrassed myself.", "I completely embarrassed myself trying to open a push door for a full minute."),
        ("Everybody was staring at me.", "My phone alarm went off mid-presentation and everybody was staring at me."),
        ("I didn't know where to look.", "When they started arguing at dinner, I didn't know where to look."),
        ("I was dying inside.", "I forgot his name right after he told me — I was dying inside."),
        ("I froze.", "The interviewer asked my biggest weakness and I just froze."),
        ("I panicked.", "The fire drill started right as I was mid-sentence, and I panicked."),
        ("That was not a good look.", "Falling asleep on the train and drooling on a stranger's shoulder — that was not a good look."),
        ("I instantly knew I messed up.", "The second I hit send on that email, I instantly knew I messed up."),
     ]),
    ("Self-Deprecating Humor",
     "You're joking about your own mistake or shortcoming in a light, self-deprecating way.",
     "used to poke fun at your own mistake or shortcoming, lightly",
     [
        ("Classic me.", "Forgot my own umbrella on the one rainy day this week. Classic me."),
        ("I'm not exactly good at this.", "I'm not exactly good at this — my houseplants keep dying no matter what I do."),
        ("I had no clue what I was doing.", "I said yes to hosting the trivia night, but I had no clue what I was doing."),
        ("I was just winging it.", "For that presentation on Friday, I was just winging it the whole time."),
        ("That sounded better in my head.", "I told him 'nice haircut, did you shrink?' — that sounded better in my head."),
        ("I totally overestimated myself.", "I signed up for the 10k thinking it'd be easy — I totally overestimated myself."),
        ("My brain just stopped working.", "She asked me a simple math question and my brain just stopped working."),
     ]),
    ("Casual Reactions of Disbelief or Frustration",
     "Something mildly annoying or surprising just happened, and you want to react casually, without making a big deal of it.",
     "used as a casual, low-stakes reaction to something surprising or mildly frustrating",
     [
        ("Seriously?", "They cancelled the trip the night before we were supposed to leave. Seriously?"),
        ("Come on.", "Come on, you can't be out of coffee again."),
        ("Give me a break.", "Another meeting got added to my calendar — give me a break."),
        ("No way.", "You got upgraded to first class for free? No way."),
        ("You've gotta be kidding me.", "The parking garage is full again? You've gotta be kidding me."),
        ("This can't be happening.", "My laptop died five minutes before the deadline — this can't be happening."),
        ("I knew it.", "I knew it — the 'quick call' turned into an hour-long meeting."),
        ("Just my luck.", "The Wi-Fi stopped working right before my meeting. Just my luck."),
     ]),
    ("Narrating Inner Thoughts",
     "You're telling a story and want to share what you were secretly thinking at the time, not what you actually said.",
     "used to share what you were privately thinking during a story, not what you said out loud",
     [
        ("In my head...", "In my head, I was already halfway out the door."),
        ("For a second, I thought...", "For a second, I thought the fire alarm was just a drill."),
        ("I was hoping nobody noticed.", "I tripped on the curb and was hoping nobody noticed."),
        ("I figured I could get away with it.", "I skipped the warm-up, figured I could get away with it."),
        ("At that point, I just wanted to go home.", "By hour three of the meeting, at that point, I just wanted to go home."),
        ("I was trying to act normal.", "My stomach was growling the whole interview and I was trying to act normal."),
        ("I pretended everything was fine.", "The call dropped mid-sentence and I pretended everything was fine when it reconnected."),
     ]),
    ("Describing Social Anxiety",
     "You're explaining to a friend how self-conscious or anxious you felt in a social situation.",
     "used to describe feeling self-conscious or anxious in a social situation",
     [
        ("I didn't want to make things awkward.", "I let the mistake slide because I didn't want to make things awkward at the party."),
        ("I was trying to keep a low profile.", "After showing up late, I was trying to keep a low profile for the rest of the meeting."),
        ("I didn't want to look stupid.", "I nodded along even though I didn't understand, because I didn't want to look stupid."),
        ("I was overthinking everything.", "I rewrote that text message five times — I was overthinking everything."),
        ("I was hoping someone else would say something.", "Nobody asked the obvious question, and I was hoping someone else would say something."),
        ("I tried to play it cool.", "My name got mispronounced for the third time and I tried to play it cool."),
     ]),
    ("Funny Exaggeration",
     "You want to exaggerate for comic effect while telling a story, rather than describe things literally.",
     "used to exaggerate for comic effect while telling a casual story",
     [
        ("It felt like forever.", "The elevator was stuck for maybe two minutes, but it felt like forever."),
        ("I nearly died.", "When the surprise party lights came on, I nearly died."),
        ("That aged me ten years.", "Watching my toddler almost touch the stove — that aged me ten years."),
        ("My soul left my body.", "The car behind me honked out of nowhere and my soul left my body."),
        ("I've never recovered from that.", "I still think about that karaoke performance — I've never recovered from that."),
        ("It was absolute chaos.", "Three deliveries arrived at once while the dog was loose — it was absolute chaos."),
     ]),
    ("Excuses & Self-Defense",
     "You're being lightly called out for something and want to explain yourself without sounding too defensive.",
     "used to explain yourself lightly, without sounding overly defensive",
     [
        ("To be fair...", "To be fair, nobody told me the meeting moved to 9am."),
        ("It wasn't entirely my fault.", "The cake didn't rise, but it wasn't entirely my fault — the oven's thermostat is broken."),
        ("In my defense...", "In my defense, the instructions were genuinely confusing."),
        ("That's not what it looked like.", "I know it looks bad, but that's not what it looked like."),
        ("I can explain.", "I know I'm two hours late — I can explain."),
        ("Technically...", "Technically, I did reply to the email, just from the wrong account."),
     ]),
    ("Natural Conversation Fillers",
     "You're chatting casually and need a natural filler to ease into your next sentence.",
     "used as a natural conversational filler when easing into the next point",
     [
        ("You know...", "You know, I never actually liked pineapple on pizza."),
        ("I mean...", "I mean, it's not the worst idea, just not my favorite."),
        ("Honestly...", "Honestly, I could use a long weekend right about now."),
        ("Apparently...", "Apparently, the office is switching coffee brands next month."),
        ("Basically...", "Basically, we ended up ordering pizza instead of cooking."),
        ("For some reason...", "For some reason, my phone kept autocorrecting his name all week."),
        ("Turns out...", "Turns out, the 'urgent' email had been sitting in my spam folder."),
        ("At this point...", "At this point, I've given up trying to fix the printer myself."),
        ("To make matters worse...", "To make matters worse, it started raining right as we left the umbrella at home."),
     ]),
    ("Workplace-Friendly Casual Chunks",
     "You're talking to a coworker casually about a mix-up at work and want to sound natural, not overly formal.",
     "used to talk casually about a work mix-up, without sounding overly formal",
     [
        ("I'm still figuring it out.", "The new expense system? I'm still figuring it out, honestly."),
        ("I probably misunderstood the requirement.", "I probably misunderstood the requirement — I thought we only needed the summary slide."),
        ("That caught me off guard.", "The client's question about pricing really caught me off guard."),
        ("I completely overlooked that.", "I completely overlooked that the form needed a manager's signature."),
        ("I got carried away.", "I got carried away formatting the slides and lost track of time."),
        ("That escalated quickly.", "One typo in the announcement and that escalated quickly."),
        ("I'm trying to keep up.", "With three projects overlapping this week, I'm trying to keep up."),
        ("I need a minute to process this.", "That's a lot of new information — I need a minute to process this."),
     ]),
    ("Wrapping Up a Story",
     "You've just finished telling a story and want to wrap it up naturally.",
     "used to wrap up a casual story naturally at the end",
     [
        ("So yeah, that was fun.", "So yeah, that was fun — never again doing a potluck with no RSVPs."),
        ("Not my proudest moment.", "Falling asleep during the movie I picked — not my proudest moment."),
        ("Lesson learned.", "I double-check the address now. Lesson learned."),
        ("Never doing that again.", "Assembling furniture at midnight — never doing that again."),
        ("Looking back now, it was actually pretty funny.", "At the time it was mortifying, but looking back now, it was actually pretty funny."),
        ("Needless to say, I learned my lesson.", "Needless to say, I learned my lesson about packing the night before a flight."),
        ("That's a story for another day.", "What happened at the office party last year? That's a story for another day."),
     ]),
    ("Golden Native Storytelling Chunks",
     "You're telling a casual story and need an idiomatic way to describe what you did or how you felt in the moment.",
     "used as an idiomatic way to describe an action or feeling inside a casual story",
     [
        ("I wasn't about to...", "I wasn't about to admit I'd forgotten his name."),
        ("I ended up...", "I ended up staying two extra hours to help set everything back up."),
        ("I got stuck...", "I got stuck explaining the joke, which made it even less funny."),
        ("I talked myself into it.", "I wasn't going to sign up for the marathon, but I talked myself into it."),
        ("I talked myself out of it.", "I almost texted him back immediately, then talked myself out of it."),
        ("I had a feeling...", "I had a feeling the meeting would run long, and it did."),
        ("I couldn't help but...", "I couldn't help but laugh when the dog stole the sandwich."),
        ("That threw me off.", "The sudden change of plans really threw me off."),
        ("I totally blanked.", "She asked my order and I totally blanked on what I wanted."),
     ]),
    ("Storytelling Twist Patterns",
     "You're telling a story and need a template to set up an expectation right before revealing what actually happened.",
     "used as a template to set up an expectation right before the twist in a story",
     [
        ("I thought X... turns out Y.", "I thought the meeting would be quick. Turns out it lasted three hours."),
        ("I was trying to X, but...", "I was trying to sound confident, but my voice was shaking."),
        ("At that point...", "At that point, I just accepted my fate."),
     ]),
    ("Modern Everyday Overwhelm",
     "A friend asks how you're doing, and honestly, you're overwhelmed or exhausted — you want to say so casually.",
     "used to casually describe feeling overwhelmed, tired, or burnt out",
     [
        ("I'm just trying to survive.", "Finals week, three deadlines, no sleep — I'm just trying to survive."),
        ("I'm barely functioning.", "It's only Tuesday and I'm barely functioning."),
        ("I'm running on zero sleep.", "The baby was up all night, so I'm running on zero sleep."),
        ("Today is not my day.", "Spilled coffee on my shirt right before the interview — today is not my day."),
        ("I can't catch a break.", "First the car, now the washing machine — I can't catch a break."),
        ("I'm hanging in there.", "It's been a rough week, but I'm hanging in there."),
        ("I overthink everything.", "I rewrote that one email four times — I overthink everything."),
        ("I got in my own head.", "Right before the presentation, I got in my own head."),
        ("I was spiraling.", "One bad review and I was spiraling for the rest of the day."),
        ("My social battery is dead.", "After three back-to-back calls, my social battery is dead."),
        ("I can't people today.", "I love you all, but I can't people today."),
        ("I need to recharge.", "I'm skipping the after-work drinks — I need to recharge."),
     ]),
    ("Low-Energy Sarcasm",
     "Something annoying just happened and you want to react with dry, low-energy sarcasm instead of getting visibly upset.",
     "used to react to something annoying with dry, low-energy sarcasm",
     [
        ("Well, that was helpful.", "The instructions just said 'figure it out.' Well, that was helpful."),
        ("Great. Just great.", "The printer's out of toner again. Great. Just great."),
        ("Love that for me.", "My flight got delayed by three hours. Love that for me."),
        ("This is fine.", "The laptop's overheating and the deadline's in an hour — this is fine."),
        ("Could this day get any worse?", "First the rain, now the flat tire — could this day get any worse?"),
        ("Sounds about right.", "They double-booked the room again. Sounds about right."),
        ("Perfect.", "Traffic on the one day I actually left early. Perfect."),
     ]),
    ("Extremely Native Mini-Chunks",
     "You want to casually acknowledge something in as few words as possible, the way a native speaker would.",
     "used as a very short, native-sounding way to casually acknowledge something",
     [
        ("Fair enough.", "You'd rather stay in tonight? Fair enough."),
        ("That tracks.", "He was late again? That tracks."),
        ("Not ideal.", "We're out of milk the morning we have guests — not ideal."),
        ("Could be worse.", "We missed the train, but could be worse — the next one's in ten minutes."),
        ("I'll take it.", "It's not the answer I wanted, but I'll take it."),
        ("That checks out.", "You said you were running late and here you are, ten minutes late. That checks out."),
        ("Makes sense.", "You skipped breakfast? Makes sense you're starving now."),
        ("That's on me.", "I forgot to send the invite — that's on me."),
        ("My bad.", "Wrong group chat, my bad."),
     ]),
    ("Softening Negative Emotions",
     "You felt genuinely angry about something, but want to describe it in a softer, less dramatic way.",
     "used to describe a negative feeling in a softer, less dramatic way than saying you were 'angry'",
     [
        ("I was kinda annoyed.", "When they cancelled last minute, I was kinda annoyed, honestly."),
        ("I was a little upset.", "The plan changed without a heads-up, and I was a little upset."),
        ("It bothered me a bit.", "He read my message and didn't reply for two days — it bothered me a bit."),
        ("I wasn't thrilled about it.", "They moved my desk without asking — I wasn't thrilled about it."),
     ]),
    ("Handling Video-Call Mishaps",
     "Something unexpected just happened on a video call — a mishap, a technical glitch, an interruption — and you need a natural, easygoing way to handle it.",
     "used to handle an unexpected mishap or glitch on a video call, casually and without stress",
     [
        ("Hey — sounds like someone's excited. Want me to wait?", "When his dog started barking on camera, I just said, 'Hey — sounds like someone's excited. Want me to wait?'"),
        ("No big deal — kids are kids. We can pause.", "Her toddler wandered into frame, so I told her, 'No big deal — kids are kids. We can pause.'"),
        ("Whoops — wrong tab. Give me two seconds.", "I shared the wrong window by mistake and said, 'Whoops — wrong tab. Give me two seconds.'"),
        ("Okay, fixed. Sorry — my desktop's a warzone.", "Once I closed the extra windows, I said, 'Okay, fixed. Sorry — my desktop's a warzone.'"),
        ("Yeah, loud and clear. You good?", "When he asked if I could hear him, I said, 'Yeah, loud and clear. You good?'"),
        ("Looks like Zoom died. I'll restart — call you back?", "The call froze completely, so I typed, 'Looks like Zoom died. I'll restart — call you back?'"),
        ("Let's switch to phone. My number's...", "Since the video kept cutting out, I said, 'Let's switch to phone. My number's 555-0148.'"),
        ("Got your message — let me simplify: it's basically X does Y. Make sense?", "When the client said 'I don't get it' in the chat, I replied, 'Got your message — let me simplify: it's basically the app syncs your files automatically. Make sense?'"),
     ]),
    ("Casual Travel & Food Small Talk",
     "You're spending casual time with a guest or friend — showing them around, cooking together, or planning an outing — and want to chat naturally about it.",
     "used for casual small talk while showing a guest around, cooking, or planning a trip together",
     [
        ("I'll show them how to prepare it step by step: first, we'll lay down fresh herbs, then add meat, and some toppings like cucumber or slices of mango.", "For our cooking demo today, I'll show them how to prepare it step by step: first, we'll lay down fresh herbs, then add meat, and some toppings like cucumber or slices of mango."),
        ("The fresh ingredients are mild, and the sauce really boosts the flavor.", "Try a bite — the fresh ingredients are mild, and the sauce really boosts the flavor."),
        ("Do you get motion sickness easily? If you do, let me know, and we can take a break or go a bit slower.", "Before we head out on the boat, do you get motion sickness easily? If you do, let me know, and we can take a break or go a bit slower."),
        ("Should we leave earlier to watch the sunset?", "Should we leave earlier to watch the sunset, before the crowds show up?"),
        ("The canoe ride takes longer than expected.", "Heads up, the canoe ride takes longer than expected, so bring some water."),
        ("Do you have everything you need, or should we pick up something before we go?", "Do you have everything you need, or should we pick up something before we go — sunscreen, snacks, anything?"),
     ]),
]

if __name__ == "__main__":
    generate_topic(
        out_path=OUT_PATH,
        exam_id="everyday-social",
        title="Chunk Atlas — Situations: Everyday & Social",
        tier_id=TIER_ID,
        tier_name=TIER_NAME,
        groups_def=groups_def,
    )
