import os
import sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, SCRIPT_DIR)
from lib import generate_topic

OUT_PATH = os.path.join(SCRIPT_DIR, "..", "data", "information-packaging.json")

# Phrase content copied by hand from the "Information Packaging" topic
# (tier "mastery" / nav tab "Language Systems") — sections M5.1-M5.8.
# M5.4's and M5.5's "c" (comparison) items and "n" (note) items are skipped
# per spec, keeping only real quotable "i" chunks. M5.1 is split into two
# finer entries (What-clefts vs The-clefts, which bundle the minimizer
# clefts too, since they share the same noun-headed framing). M5.6, M5.7
# and M5.8 each bundle multiple distinct functions, so each is split into
# 2-3 finer groups, mirroring the reference script's H14 split.
TIER_ID = "mastery"
TIER_NAME = "Language Systems"

groups_def = [
    ("Wh-clefts: highlighting via What",
     "You want to put the important new information at the very end of the sentence, so you open the sentence with a 'What...' clause instead of leading with it.",
     "used to push the key new information to the end of the sentence by opening with a What-clause",
     [
        ("What I mean is...", "What I mean is we should test with real users before committing budget."),
        ("What matters here is...", "What matters here is whether customers actually renew, not how many sign up."),
        ("What struck me was...", "What struck me was how calm the team stayed during the outage."),
        ("What worries me is...", "What worries me is we still don't have a rollback plan."),
        ("What we need to do is...", "What we need to do is get legal's sign-off before we announce anything."),
        ("What surprised me most was...", "What surprised me most was how quickly support tickets dropped after the fix."),
        ("What it comes down to is...", "What it comes down to is whether we trust the vendor's timeline."),
     ]),
    ("Clefts: highlighting via The + noun",
     "You want to name the single most important idea as a noun before you explain it, using a 'The ... is' frame instead of a plain statement.",
     "used to spotlight one key idea with a noun-headed 'The ... is' frame before elaborating on it",
     [
        ("The thing is...", "The thing is, we promised this feature for Friday and it's not ready."),
        ("The point is...", "The point is we can't launch without a rollback plan."),
        ("The problem is...", "The problem is nobody owns this ticket anymore."),
        ("The reality is...", "The reality is we're going to miss the deadline either way."),
        ("The question is...", "The question is whether we tell the client now or wait until Monday."),
        ("All I'm saying is...", "All I'm saying is we should double-check the numbers before sending them."),
        ("The only thing I'd add is...", "The only thing I'd add is that we should loop in support before the release."),
        ("One thing to flag is...", "One thing to flag is that the API limit resets at midnight UTC, not local time."),
     ]),
    ("It-clefts: highlighting via It was...that",
     "You want to isolate one specific element as the real cause or focus, using an 'It was/is ... that' frame instead of a plain statement.",
     "used to isolate one specific element as the focus or cause, framed as 'It was/is ... that'",
     [
        ("It was X that/who...", "It was the timing that concerned me, not the cost."),
        ("It's not until... that...", "It's not until you present that you spot the gaps."),
        ("It's X that makes the difference.", "It's the follow-up call that makes the difference, not the first email."),
        ("It's precisely because... that...", "It's precisely because the client is nervous that we need to over-communicate."),
        ("It's worth noting that...", "It's worth noting that this only affects users on the old plan."),
        ("It's no coincidence that...", "It's no coincidence that churn spiked right after we changed the pricing page."),
        ("It's no accident that...", "It's no accident that our best-performing team also runs the shortest meetings."),
     ]),
    ("Fronting & inversion (formal emphasis)",
     "You want to emphasize a point in a formal, almost dramatic way by moving a negative or limiting word to the front of the sentence, which forces the subject and verb to swap order.",
     "used for formal, emphatic fronting where a negative or limiting element moves to the front and triggers subject-verb inversion",
     [
        ("Only then did I realise...", "Only then did I realise we'd been testing on the wrong environment."),
        ("Only after the review did we see the gap.", "Only after the review did we see the gap between what was promised and what was built."),
        ("Not once did they mention...", "Not once did they mention the budget cut during the entire call."),
        ("Never (before) have I seen...", "Never before have I seen a rollout go this smoothly."),
        ("Rarely do we get a chance like this.", "Rarely do we get a chance like this to rebuild the pricing model from scratch."),
        ("Such was the impact that...", "Such was the impact that two clients renewed early just to lock in the old price."),
        ("So critical is this that...", "So critical is this that we're pausing every other project until it's fixed."),
        ("Had we known earlier, we would have...", "Had we known earlier, we would have pushed the launch back a week."),
        ("This much is clear: ...", "This much is clear: we can't keep shipping without QA sign-off."),
        ("One thing is certain: ...", "One thing is certain: the current process doesn't scale past ten clients."),
     ]),
    ("End-weight & extraposition",
     "You want to comment on an action or idea, so you push the heavy part of the sentence to the end and open instead with a light 'It' or 'There'.",
     "used to move a long, heavy subject to the end of the sentence, opening instead with a light 'It' or 'There'",
     [
        ("It's important to...", "It's important to loop in legal before you sign anything."),
        ("There's no point (in) -ing", "There's no point in rushing the release if QA hasn't signed off."),
        ("It's worth -ing", "It's worth double-checking the numbers before the board meeting."),
        ("It makes sense to...", "It makes sense to pilot this with one team before rolling it out company-wide."),
        ("There's something to be said for...", "There's something to be said for keeping the meeting short, even if it feels rushed."),
        ("It goes without saying that...", "It goes without saying that we need sign-off before touching production."),
        ("It remains to be seen whether...", "It remains to be seen whether the new pricing actually reduces churn."),
     ]),
    ("Passive & agentless framing (diplomatic distance)",
     "You need to report a mistake or piece of bad news to the group without naming exactly who is responsible, to keep the tone diplomatic.",
     "used to report a problem while removing the responsible person from the sentence, to soften criticism",
     [
        ("Mistakes were made.", "Mistakes were made during the migration, and we're now auditing every step."),
        ("The deadline was missed.", "The deadline was missed, and we're already drafting a revised timeline."),
        ("It was decided that...", "It was decided that the launch would be delayed by one week."),
        ("There seems to have been a misunderstanding.", "There seems to have been a misunderstanding about who owns the QA sign-off."),
        ("Something got lost in translation.", "Something got lost in translation between the design brief and the final build."),
        ("It's been suggested that...", "It's been suggested that we merge the two support queues."),
        ("Concerns have been raised about...", "Concerns have been raised about the vendor's ability to meet the new deadline."),
     ]),
    ("Highlighting the key takeaway",
     "You're about to name the single most important fact from everything you've just explained.",
     "used to flag the single most important fact after a longer explanation",
     [
        ("The key thing here is...", "The key thing here is that support tickets dropped 40% after the fix."),
        ("The one thing I'd flag is...", "The one thing I'd flag is that the new vendor hasn't confirmed the SLA yet."),
        ("If there's one takeaway...", "If there's one takeaway, it's that we need a single source of truth for this data."),
        ("What's interesting is...", "What's interesting is that mobile users convert twice as often as desktop."),
        ("What's worrying is...", "What's worrying is that this is the third outage this quarter."),
        ("What's changed is...", "What's changed is that our biggest competitor just dropped their prices by 20%."),
        ("This is the important bit.", "This is the important bit: the discount only applies to annual plans."),
        ("If you take nothing else away: ...", "If you take nothing else away: back up the database before you run this script."),
     ]),
    ("Signposting what's coming / cueing the listener",
     "You're about to explain something that takes a few steps, and you want to prepare the listener before you start.",
     "used to prepare the listener for an explanation that takes a few steps, or has a twist",
     [
        ("Here's where it gets complicated.", "Here's where it gets complicated: the two systems use different timestamp formats."),
        ("Here's the tricky part.", "Here's the tricky part — legal needs to sign off before we can even test this."),
        ("Here's the catch.", "Here's the catch: the discount only works if they pay annually."),
        ("The short version is...", "The short version is: we're a week behind, but it's recoverable."),
        ("The long version is...", "The long version is a bit more complicated — it involves three different teams."),
        ("The honest version is...", "The honest version is we underestimated how long QA would take."),
        ("Two things. One: ... Two: ...", "Two things. One: the budget is approved. Two: we still need a project lead."),
        ("There's a but coming.", "The numbers look great — but there's a but coming."),
        ("Bear with me on this one.", "Bear with me on this one, the explanation takes a couple of steps."),
        ("Stay with me.", "Stay with me — this gets a little technical before it gets simple again."),
     ]),
    ("Formal transition connectors: concession & evaluation",
     "You've just made a point, and now you want to add a qualifying or concessive comment before moving on, in a formal register.",
     "used in a formal register to add a concessive or evaluative comment after making a point",
     [
        ("That said", "That said, the client did approve the revised timeline."),
        ("Having said that", "Having said that, I still think we should test with a smaller group first."),
        ("Then again", "Then again, we did say we'd prioritize speed over polish this quarter."),
        ("All the same", "All the same, I'd like to see the numbers before we commit."),
        ("On balance", "On balance, the pilot was a success, even with the rocky first week."),
        ("All things considered", "All things considered, we shipped this faster than I expected."),
        ("Taking everything into account", "Taking everything into account, vendor B is still the safer choice."),
     ]),
    ("Formal transition connectors: addition & comparison",
     "You want to add a formal transition that either builds on your last point or draws a parallel or contrast with it.",
     "used in a formal register to add to, escalate, or draw a parallel with the previous point",
     [
        ("More to the point", "More to the point, we still haven't tested this on mobile."),
        ("Better still", "Better still, the fix also reduced our server costs."),
        ("Worse still", "Worse still, the bug affects our biggest client's account."),
        ("What's more", "What's more, the new flow cut onboarding time in half."),
        ("By the same token", "By the same token, we should hold marketing to the same deadline."),
        ("In much the same way", "In much the same way, the support team needs a single dashboard too."),
        ("Conversely", "Conversely, smaller clients barely noticed the price change."),
        ("Equally", "Equally, we can't ignore the feedback from our most loyal users."),
     ]),
    ("Formal transition connectors: consequence & purpose",
     "You want to connect a formal conclusion or next step to what you just said.",
     "used in a formal register to connect a consequence or next step to what was just said",
     [
        ("Which brings me to...", "Which brings me to my next point: we need a backup vendor."),
        ("Which is exactly why...", "Which is exactly why we're proposing a phased rollout."),
        ("Hence", "Hence the decision to delay the launch by a week."),
        ("Thereby", "We automated the check-in step, thereby cutting onboarding time in half."),
        ("To that end", "To that end, we're hiring two more QA engineers this quarter."),
        ("With that in mind", "With that in mind, let's build in an extra buffer week."),
        ("On that basis", "On that basis, I'd recommend we go with vendor B."),
        ("In light of that", "In light of that, we're revising our Q3 targets."),
     ]),
    ("Personal viewpoint framing",
     "You want to preface your personal opinion clearly, so the listener knows this is your view, not a stated fact.",
     "used to preface a personal opinion so the listener knows it's a view, not a stated fact",
     [
        ("The way I see it...", "The way I see it, speed matters more than perfection right now."),
        ("As far as I'm concerned...", "As far as I'm concerned, the pilot already proved the concept."),
        ("From where I sit...", "From where I sit, the bigger risk is losing the client, not missing the date."),
        ("If I'm being honest...", "If I'm being honest, I don't think we're ready to launch yet."),
        ("If you want my view...", "If you want my view, we should cut scope, not extend the deadline."),
        ("Between you and me...", "Between you and me, I think the vendor is stalling."),
        ("The truth is...", "The truth is, we underestimated how long the migration would take."),
        ("The fact of the matter is...", "The fact of the matter is our support team is understaffed for this volume."),
     ]),
    ("Getting to the core issue / offering a way forward",
     "You want to name the real underlying issue, or propose a concrete next step, after a longer discussion.",
     "used to name the underlying issue or propose a concrete next step after a discussion",
     [
        ("It boils down to...", "It boils down to trust — the two teams just don't trust each other's estimates."),
        ("It comes down to...", "It comes down to whether we have the budget for a third engineer."),
        ("It all hinges on...", "It all hinges on whether legal approves the new contract terms."),
        ("The problem with that is...", "The problem with that is it doubles our support workload."),
        ("The risk there is...", "The risk there is we lose the client if we push the date again."),
        ("The catch is...", "The catch is the discount only applies to new customers."),
        ("What I'd suggest is...", "What I'd suggest is we run a two-week pilot before committing fully."),
        ("What I'd do is...", "What I'd do is split the release into two smaller phases."),
        ("My instinct would be to...", "My instinct would be to delay the launch rather than cut testing."),
     ]),
    ("Flagging uncertainty & precision",
     "You want to flag a possible gap in your own understanding, or make sure your point can't be misread.",
     "used to flag a possible gap in understanding, or to make a point impossible to misread",
     [
        ("Correct me if I'm wrong, but...", "Correct me if I'm wrong, but I thought QA already signed off on this."),
        ("Unless I'm missing something...", "Unless I'm missing something, this contradicts what we agreed last week."),
        ("Just so we're clear...", "Just so we're clear, this change only affects the EU region."),
        ("To be absolutely clear...", "To be absolutely clear, we are not extending the deadline again."),
        ("Let me be blunt...", "Let me be blunt: at this pace, we will miss the launch date."),
     ]),
]

if __name__ == "__main__":
    generate_topic(
        out_path=OUT_PATH,
        exam_id="information-packaging",
        title="Chunk Atlas — Language Systems: Information Packaging",
        tier_id=TIER_ID,
        tier_name=TIER_NAME,
        groups_def=groups_def,
    )
