import os
import sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, SCRIPT_DIR)
from lib import generate_topic

OUT_PATH = os.path.join(SCRIPT_DIR, "..", "data", "vague-approximative.json")

# Phrase content copied by hand from the "Vague & Approximative Language"
# topic (tier "mastery" / nav tab "Language Systems") — sections M7.1-M7.6
# (+L7.6 continuation). "c" and "n" items are skipped per spec. Each
# header's comma/slash-separated lines are already tight sub-themes, so
# most map close to 1:1 to a group (M7.1-M7.4 split by their own labeled
# or unlabeled sub-lines). M7.5 and M7.6 are each a single coherent
# function in the source (deflecting a question / staying non-committal);
# M7.6 is split into two finer groups (deferring vs. a soft conditional
# yes) since it bundles two distinct moves.
TIER_ID = "mastery"
TIER_NAME = "Language Systems"

groups_def = [
    ("Approximating with -ish",
     "You want to give a rough time, color, or feeling casually by adding '-ish' to a word, instead of stating it exactly.",
     "an informal '-ish' suffix used to make a word approximate rather than exact",
     [
        ("fiveish", "Let's say fiveish, I might be a few minutes late."),
        ("blueish", "The old logo was more blueish than the navy we use now."),
        ("tallish", "He's tallish, maybe just under six foot."),
        ("tiredish", "I'm feeling a bit tiredish after the red-eye flight."),
        ("Mondayish", "I should have the draft ready Mondayish."),
     ]),
    ("Approximating amounts casually",
     "You want to give a casual, rounded number or amount instead of an exact figure.",
     "a casual approximator used to round a number or amount instead of stating it exactly",
     [
        ("or so", "It'll take an hour or so to finish the report."),
        ("or thereabouts", "The office holds fifty people, or thereabouts."),
        ("give or take", "The migration took six hours, give or take."),
        ("roughly", "Roughly half the team has tried the new tool."),
        ("around", "We spent around three thousand dollars on the offsite."),
        ("about", "The meeting should last about forty minutes."),
     ]),
    ("Approximating amounts at work",
     "You want to give a rough figure in a slightly more polished, workplace register than a casual 'or so'.",
     "a workplace-register approximator used to give a rough figure without sounding too casual",
     [
        ("in the region of", "The contract is worth something in the region of two hundred thousand."),
        ("something like", "We're looking at something like a two-week delay."),
        ("in the ballpark of", "Their quote came in the ballpark of what we budgeted."),
        ("north of", "Headcount for this project is now north of fifteen people."),
        ("south of", "The final invoice came in south of our original estimate."),
     ]),
    ("Rough workplace estimates",
     "You want to explicitly flag that a number you're giving is a rough calculation, not a precise one.",
     "used to explicitly flag a number as a rough calculation rather than a precise figure",
     [
        ("a rough estimate", "This is just a rough estimate — I'll confirm the exact cost tomorrow."),
        ("back-of-the-envelope", "That's a back-of-the-envelope number, don't quote me on it."),
        ("order of magnitude", "We're talking about an order of magnitude more traffic than last year."),
     ]),
    ("Open-ended list extenders (casual)",
     "You've listed a couple of examples and want to signal there are more of the same kind, without listing every single one.",
     "a casual list-ending phrase signaling more unlisted examples of the same kind",
     [
        ("and so on", "We covered pricing, onboarding, support, and so on."),
        ("and so forth", "The kit includes cables, adapters, and so forth."),
        ("and that kind of thing", "She handles vendor contracts, renewals, and that kind of thing."),
        ("and stuff like that", "We talked about the roadmap, budget, and stuff like that."),
        ("or something", "Maybe we grab coffee or something before the call."),
     ]),
    ("Open-ended list extenders (informal)",
     "You've listed a couple of examples in a relaxed, informal conversation and want to trail off instead of listing everything.",
     "an informal list-ending phrase signaling more unlisted examples of the same kind",
     [
        ("and whatnot", "He handles the servers, the backups, and whatnot."),
        ("and the like", "We use Slack, Notion, and the like for daily comms."),
        ("and all that", "We covered pricing, timelines, and all that."),
        ("you name it", "Bugs, delays, angry clients — you name it, we've had it this month."),
        ("that sort of thing", "She's great with spreadsheets, reports, that sort of thing."),
     ]),
    ("Open-ended list extenders (workplace)",
     "You're listing familiar workplace items or people and want to signal the rest are the usual, predictable ones.",
     "a workplace list-ending phrase signaling the rest are the usual, predictable items",
     [
        ("and the usual suspects", "The client escalation included finance, legal, and the usual suspects."),
        ("and everything that goes with it", "We're taking on the migration and everything that goes with it."),
        ("and downstream of that", "This affects billing, and downstream of that, customer support too."),
     ]),
    ("Vague quantity expressions",
     "You want to describe a quantity casually without giving an exact number.",
     "a casual, imprecise way of describing a quantity without giving an exact number",
     [
        ("a couple of", "I made a couple of small tweaks to the deck."),
        ("a fair few", "A fair few customers asked about the mobile app this week."),
        ("a handful of", "Only a handful of people showed up to the optional session."),
        ("a bit of", "There's a bit of confusion about who owns this ticket."),
        ("loads of", "We got loads of feedback after the beta launch."),
        ("tons of", "There are tons of edge cases we haven't tested yet."),
        ("a smattering of", "There's a smattering of typos left in the draft."),
        ("one or two", "One or two clients mentioned the checkout was slow."),
     ]),
    ("Placeholder words for forgotten names",
     "You've forgotten the exact name of a person or object and need a placeholder word to keep talking.",
     "an informal placeholder word used when the speaker has forgotten the exact name",
     [
        ("thingy", "Can you pass me that thingy that connects to the projector?"),
        ("whatsit", "Where's the whatsit that resets the router?"),
        ("thingamajig", "He fixed it with some thingamajig from the hardware store."),
        ("so-and-so", "She said, quote, so-and-so promised this last week, unquote."),
        ("what's-his-name", "What's-his-name from procurement finally called back."),
     ]),
    ("Diplomatically vague quantities",
     "You want to mention a small number of complaints or people without naming exactly who or how many, to protect someone's reputation.",
     "a deliberately vague quantity used to protect someone's reputation instead of naming exact numbers or names",
     [
        ("certain stakeholders", "Certain stakeholders raised concerns about the new process."),
        ("some parties", "Some parties weren't happy with how the announcement was handled."),
        ("one or two concerns", "There have been one or two concerns about response times."),
     ]),
    ("Vague time expressions",
     "You want to give a rough sense of when something will happen without committing to an exact time.",
     "a casual, imprecise way of referring to timing without committing to an exact time",
     [
        ("in a bit", "I'll send the notes over in a bit."),
        ("in a sec", "Give me a sec, I'll pull up the numbers."),
        ("shortly", "The client should be joining shortly."),
        ("at some point", "We should revisit the pricing at some point this quarter."),
        ("sooner or later", "Sooner or later we'll need to migrate off the old system."),
        ("any minute now", "The report should land any minute now."),
     ]),
    ("Vague quantity expressions (everyday)",
     "You want to describe an amount casually, in relaxed everyday conversation rather than a report.",
     "a casual, everyday way of describing an amount without giving an exact figure",
     [
        ("a bunch of", "A bunch of us are grabbing lunch after the demo."),
        ("a load of", "We got a load of signups after the newsletter went out."),
        ("a handful", "Only a handful actually finished the onboarding flow."),
        ("a fair bit", "We've spent a fair bit of time on this already."),
        ("not much", "There's not much left to do before the release."),
        ("hardly any", "Hardly any customers noticed the price change."),
     ]),
    ("Vague degree expressions",
     "You want to soften how strongly you're describing something, using a casual degree word instead of a precise measurement.",
     "a casual degree word used to soften a description instead of giving a precise measurement",
     [
        ("a touch", "The deadline feels a touch tight, but doable."),
        ("a tad", "This version runs a tad slower than the last one."),
        ("a smidge", "Could you push the meeting a smidge later?"),
        ("slightly", "Response times are slightly better since the fix."),
        ("somewhat", "The client was somewhat frustrated by the delay."),
        ("fairly", "The rollout went fairly smoothly, all things considered."),
        ("pretty", "The new dashboard is pretty close to what we pitched."),
     ]),
    ("Vague frequency expressions",
     "You want to describe how often something happens without giving an exact frequency.",
     "a casual, imprecise way of describing how often something happens",
     [
        ("now and then", "The old bug still pops up now and then."),
        ("every so often", "Every so often the client asks for a status update out of nowhere."),
        ("on and off", "We've been discussing this project on and off for months."),
        ("here and there", "There are still a few bugs here and there."),
        ("from time to time", "From time to time we get a request for a custom report."),
     ]),
    ("Vague quality expressions",
     "You want to describe how good or bad something was, casually and non-committally, without a strong evaluative word.",
     "a casual, non-committal way of describing quality without a strong evaluative word",
     [
        ("alright", "The demo went alright, nothing broke at least."),
        ("not bad", "The first draft isn't bad, just needs trimming."),
        ("decent", "We got a decent turnout for the webinar."),
        ("so-so", "Feedback on the new layout has been so-so."),
        ("could be worse", "Sales are down, but it could be worse."),
        ("nothing to write home about", "The results were nothing to write home about, honestly."),
     ]),
    ("Vague references to people",
     "You want to refer to a person casually without naming exactly who they are.",
     "a casual, imprecise way of referring to a person without naming exactly who they are",
     [
        ("someone", "Someone from finance flagged the invoice mismatch."),
        ("a mate of mine", "A mate of mine works at a similar startup and had the same issue."),
        ("this guy", "This guy on the support team fixed it in ten minutes."),
        ("a colleague", "A colleague mentioned the same bug last week."),
        ("people", "People have been asking when the feature ships."),
     ]),
    ("Vague references to place",
     "You want to refer to a location casually without naming the exact place.",
     "a casual, imprecise way of referring to a location without naming the exact place",
     [
        ("somewhere", "The server logs are stored somewhere on the old backup drive."),
        ("round here", "Nobody round here remembers why we set it up that way."),
        ("over that way", "The new office is over that way, past the parking lot."),
        ("up north", "Their biggest warehouse is up north."),
        ("down south", "We're opening a second office down south next year."),
     ]),
    ("Vague references to things",
     "You want to refer to objects or tasks casually without naming them precisely.",
     "a casual, imprecise way of referring to objects or tasks without naming them precisely",
     [
        ("stuff", "Leave your stuff by the door, we'll sort it out later."),
        ("things", "There are a few things we still need to confirm with legal."),
        ("bits and bobs", "I need to grab a few bits and bobs before the trip."),
        ("odds and ends", "We spent the afternoon tidying up odds and ends in the backlog."),
        ("this and that", "We talked about this and that, nothing urgent."),
     ]),
    ("Deflecting a direct question politely",
     "You've been asked a direct question you don't want to, or can't, answer fully, and you need to deflect politely without being rude.",
     "used to politely avoid giving a direct answer to an uncomfortable or sensitive question",
     [
        ("It's complicated.", "Why did the deal fall through? It's complicated."),
        ("It depends.", "Will this affect pricing? It depends."),
        ("There are a few moving parts.", "There are a few moving parts, so I'd rather not commit to a date yet."),
        ("I'd rather not say at this stage.", "I'd rather not say at this stage — we're still in negotiations."),
        ("That's still being worked out.", "The final terms are still being worked out."),
        ("Let's just say it wasn't ideal.", "How did the client meeting go? Let's just say it wasn't ideal."),
        ("Let's leave it there.", "Let's leave it there for now, we can pick it up next week."),
        ("Something like that.", "Did the vendor miss the deadline again? Something like that."),
        ("More or less.", "Is the budget finalized? More or less."),
        ("In a manner of speaking.", "Did we win the deal? In a manner of speaking."),
        ("I couldn't possibly comment.", "Is the CEO stepping down? I couldn't possibly comment."),
     ]),
    ("Staying non-committal / deferring a decision",
     "You're not ready to commit to a plan or answer yet, and you want to defer without shutting the door.",
     "used to defer a decision or commitment without shutting the door on it",
     [
        ("Let's see how it goes.", "We'll launch to a small group first and see how it goes."),
        ("We'll play it by ear.", "We don't have a fixed agenda, we'll play it by ear."),
        ("Let's see where we land.", "Let's see where we land after the client feedback comes in."),
        ("I'd have to check.", "I'd have to check with finance before confirming the budget."),
        ("Leave it with me.", "Leave it with me, I'll get back to you by Friday."),
        ("Let me look into it.", "Let me look into it and I'll follow up tomorrow."),
        ("It's on the radar.", "The feature request is on the radar for next quarter."),
        ("It's in the mix.", "A price increase is in the mix, but nothing's decided."),
        ("We're considering it.", "We're considering it, but no final call yet."),
     ]),
    ("Giving a soft, conditional yes",
     "You want to give a tentative 'yes' without fully committing, leaving room to change your mind later.",
     "used to give a tentative, conditional 'yes' that leaves room to change later",
     [
        ("In principle, yes.", "Can we extend the trial? In principle, yes, pending finance approval."),
        ("Broadly, yes.", "Does the new plan solve the problem? Broadly, yes."),
        ("Subject to a few things.", "We can hit that date, subject to a few things on the vendor's side."),
        ("Provisionally, yes.", "Provisionally, yes, we can commit to the March date."),
        ("Pencil it in.", "Let's pencil it in for next Thursday and confirm later."),
        ("Let's keep it loose.", "Let's keep it loose for now and firm up the agenda closer to the date."),
        ("No promises, but...", "No promises, but we'll try to get it done by Friday."),
        ("All being well...", "All being well, we'll ship this by the end of the month."),
        ("Touch wood.", "We haven't had a single bug reported yet, touch wood."),
     ]),
]

if __name__ == "__main__":
    generate_topic(
        out_path=OUT_PATH,
        exam_id="vague-approximative",
        title="Chunk Atlas — Language Systems: Vague & Approximative Language",
        tier_id=TIER_ID,
        tier_name=TIER_NAME,
        groups_def=groups_def,
    )
